var annotated_dup =
[
    [ "DynCommReticulate", "namespaceDynCommReticulate.html", "namespaceDynCommReticulate" ],
    [ "Time", "namespaceTime.html", "namespaceTime" ],
    [ "Algorithm", "classAlgorithm.html", "classAlgorithm" ],
    [ "AlgorithmBase", "classAlgorithmBase.html", "classAlgorithmBase" ],
    [ "AlgorithmInterface", "classAlgorithmInterface.html", "classAlgorithmInterface" ],
    [ "AlgorithmLouvain", "classAlgorithmLouvain.html", "classAlgorithmLouvain" ],
    [ "Criterion", "classCriterion.html", "classCriterion" ],
    [ "CriterionBalMod", "classCriterionBalMod.html", "classCriterionBalMod" ],
    [ "CriterionBase", "classCriterionBase.html", "classCriterionBase" ],
    [ "CriterionInterface", "classCriterionInterface.html", "classCriterionInterface" ],
    [ "CriterionModularity", "classCriterionModularity.html", "classCriterionModularity" ],
    [ "DummyAlgorithm", "classDummyAlgorithm.html", null ],
    [ "DummyEnum", "classDummyEnum.html", "classDummyEnum" ],
    [ "DummyQuality", "classDummyQuality.html", null ],
    [ "DynCommBase", "classDynCommBase.html", "classDynCommBase" ],
    [ "DynCommBaseInterface", "classDynCommBaseInterface.html", "classDynCommBaseInterface" ],
    [ "DynCommRcpp", "classDynCommRcpp.html", "classDynCommRcpp" ],
    [ "Edge", "classEdge.html", "classEdge" ],
    [ "GraphInterface", "classGraphInterface.html", "classGraphInterface" ],
    [ "GraphUndirected", "classGraphUndirected.html", "classGraphUndirected" ],
    [ "GraphUndirectedGroupable", "classGraphUndirectedGroupable.html", "classGraphUndirectedGroupable" ],
    [ "HalfEdge", "classHalfEdge.html", "classHalfEdge" ],
    [ "MapReversable", "classMapReversable.html", "classMapReversable" ],
    [ "MultimapReversable", "classMultimapReversable.html", "classMultimapReversable" ],
    [ "ProgramParameters", "structProgramParameters.html", "structProgramParameters" ],
    [ "ReaderDummy", "classReaderDummy.html", "classReaderDummy" ],
    [ "ReaderFileEdge", "classReaderFileEdge.html", "classReaderFileEdge" ],
    [ "ReaderInterface", "classReaderInterface.html", "classReaderInterface" ],
    [ "ReaderMatrixEdge", "classReaderMatrixEdge.html", "classReaderMatrixEdge" ],
    [ "ReaderStringEdge", "classReaderStringEdge.html", "classReaderStringEdge" ],
    [ "StringFormatter", "classStringFormatter.html", "classStringFormatter" ],
    [ "WriterFile", "classWriterFile.html", "classWriterFile" ],
    [ "WriterInterface", "classWriterInterface.html", "classWriterInterface" ],
    [ "WriterStream", "classWriterStream.html", "classWriterStream" ]
];