DynComm: GraphInterface Class Reference
GraphInterface Class Reference abstract
Interface for graph.
#include <graphInterface.h>
Public Member Functions
virtual ~GraphInterface ()
virtual typeLinksRangeConst edges () const =0
virtual bool addEdge (const typeVertex &source, const typeVertex &destination, const typeWeight &weight=1.0, const bool &replace=false)=0
virtual bool addEdge (const Edge &edge, const bool &replace=false)=0
virtual bool removeEdge (const typeVertex &source, const typeVertex &destination)=0
virtual bool removeEdge (const Edge &edge)=0
virtual const typeVertexList & getVertices () const =0
virtual typeLinksRangeConst neighbors (const typeVertex &vertex) const =0
Get the neighbors of a vertex.
virtual typeWeight neighborsWeight (const typeVertex &vertex) const =0
Get the sum of the weights of the neighbors of a vertex.
virtual unsigned int neighborsCount (const typeVertex &vertex) const =0
Get the number of neighbors of a vertex.
virtual typeWeight weight (const typeVertex &source, const typeVertex &destination) const =0
virtual const typeWeight & maxWeight () const =0
virtual const typeWeight totalWeight () const =0
virtual const typeWeight vertexCount () const =0
virtual const typeWeight edgeCount () const =0
virtual typeWeight weighted_degree (const typeVertex &node) const =0
virtual bool replace (const typeVertex &oldValue, const typeVertex &newValue)=0
virtual const std::string toString (const StringFormatter &sf=defaultStringFormatter) const =0
Detailed Description
Interface for graph.
Class that defines the interface for the graph used in DynComm.
Author
poltergeist0
Date
2018-08-19
Definition at line 112 of file graphInterface.h.
Constructor & Destructor Documentation
~GraphInterface()
virtual GraphInterface::~GraphInterface () inline virtual
Destructor
Definition at line 117 of file graphInterface.h.
References addEdge(), defaultStringFormatter, edgeCount(), edges(), getVertices(), maxWeight(), neighbors(), neighborsCount(), neighborsWeight(), removeEdge(), replace(), toString(), totalWeight(), vertexCount(), weight(), and weighted_degree().
Member Function Documentation
addEdge() [1/2]
virtual bool GraphInterface::addEdge (const typeVertex & source, const typeVertex & destination, const typeWeight & weight = 1.0, const bool & replace = false) pure virtual
Add an edge
Parameters
source
destination
weight Default value is one
replace if true and link exists, it replaces the weight, otherwise fails. Default value is false
Returns
true if the edge was added. False otherwise
Implemented in GraphUndirectedGroupable, and GraphUndirected.
Referenced by ~GraphInterface().
addEdge() [2/2]
virtual bool GraphInterface::addEdge (const Edge & edge, const bool & replace = false) pure virtual
Add an edge
Parameters
edge
replace if true and link exists, it replaces the weight, otherwise fails. Default value is false
Returns
true if the edge was added. False otherwise
Implemented in GraphUndirectedGroupable, and GraphUndirected.
edgeCount()
virtual const typeWeight GraphInterface::edgeCount () const pure virtual
Returns
the number of edges in the graph
Implemented in GraphUndirected.
Referenced by ~GraphInterface().
edges()
virtual typeLinksRangeConst GraphInterface::edges () const pure virtual
Returns
a pair with iterators to the beginning and end of the edge list.
Implemented in GraphUndirected.
Referenced by ~GraphInterface().
getVertices()
virtual const typeVertexList& GraphInterface::getVertices () const pure virtual
Returns
all unique vertices in the graph
Implemented in GraphUndirected.
Referenced by ~GraphInterface().
maxWeight()
virtual const typeWeight& GraphInterface::maxWeight () const pure virtual
Returns
the largest weight of all edges in the graph
Implemented in GraphUndirected.
Referenced by ~GraphInterface().
neighbors()
virtual typeLinksRangeConst GraphInterface::neighbors (const typeVertex & vertex) const pure virtual
Get the neighbors of a vertex.
The pair can change between calls if the Indexed edge list is modified.
Parameters
vertex
Returns
pointers to the first and last neighbor of the vertex
Implemented in GraphUndirected.
Referenced by ~GraphInterface().
neighborsCount()
virtual unsigned int GraphInterface::neighborsCount (const typeVertex & vertex) const pure virtual
Get the number of neighbors of a vertex.
Parameters
vertex
Returns
the number of neighbors of the given vertex
Implemented in GraphUndirected.
Referenced by ~GraphInterface().
neighborsWeight()
virtual typeWeight GraphInterface::neighborsWeight (const typeVertex & vertex) const pure virtual
Get the sum of the weights of the neighbors of a vertex.
Parameters
vertex
Returns
the sum of the weights of the neighbors of the given vertex
Implemented in GraphUndirected.
Referenced by ~GraphInterface().
removeEdge() [1/2]
virtual bool GraphInterface::removeEdge (const typeVertex & source, const typeVertex & destination) pure virtual
remove an edge
Parameters
source
destination
Returns
true if the edge existed and was successfully removed
Implemented in GraphUndirectedGroupable, and GraphUndirected.
Referenced by ~GraphInterface().
removeEdge() [2/2]
virtual bool GraphInterface::removeEdge (const Edge & edge) pure virtual
See also
{removeEdge(const typeVertex & source, const typeVertex & destination)}
Parameters
edge
Returns
Implemented in GraphUndirectedGroupable, and GraphUndirected.
replace()
virtual bool GraphInterface::replace (const typeVertex & oldValue, const typeVertex & newValue) pure virtual
Replace all vertex occurrences of oldValue by newValue
Parameters
oldValue
newValue
Returns
true if replacement succeeded
Implemented in GraphUndirectedGroupable, and GraphUndirected.
Referenced by ~GraphInterface().
toString()
virtual const std::string GraphInterface::toString (const StringFormatter & sf = defaultStringFormatter) const pure virtual
Returns
a string representation of this graph
Implemented in GraphUndirectedGroupable, and GraphUndirected.
Referenced by ~GraphInterface().
totalWeight()
virtual const typeWeight GraphInterface::totalWeight () const pure virtual
Returns
the sum of the weight of all edges in the graph
Implemented in GraphUndirected.
Referenced by ~GraphInterface().
vertexCount()
virtual const typeWeight GraphInterface::vertexCount () const pure virtual
Returns
the number of vertices in the graph
Implemented in GraphUndirected.
Referenced by ~GraphInterface().
weight()
virtual typeWeight GraphInterface::weight (const typeVertex & source, const typeVertex & destination) const pure virtual
Returns
the weight of the edge
Implemented in GraphUndirected.
Referenced by ~GraphInterface().
weighted_degree()
virtual typeWeight GraphInterface::weighted_degree (const typeVertex & node) const pure virtual
Parameters
vertex
Returns
the weighted degree (sum of weights of the neighbors) of the given vertex
Implemented in GraphUndirected.
Referenced by ~GraphInterface().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/graphInterface.h