DynComm: GraphUndirected Class Reference
GraphUndirected Class Reference
Graph.
#include <graphUndirected.h>
Public Member Functions
GraphUndirected ()
GraphUndirected (const GraphUndirected &original)
typeLinksRangeConst edges () const
bool addEdge (const typeVertex &source, const typeVertex &destination, const typeWeight &weight=1.0, const bool &replace=false)
bool addEdge (const Edge &edge, const bool &replace=false)
bool removeEdge (const typeVertex &source, const typeVertex &destination)
bool removeEdge (const Edge &edge)
const typeVertexList & getVertices () const
typeLinksRangeConst neighbors (const typeVertex &vertex) const
Get the neighbors of a vertex.
typeWeight neighborsWeight (const typeVertex &vertex) const
Get the sum of the weights of the neighbors of a vertex.
unsigned int neighborsCount (const typeVertex &vertex) const
Get the number of neighbors of a vertex.
typeWeight weight (const typeVertex &source, const typeVertex &destination) const
const typeWeight & maxWeight () const
const typeWeight totalWeight () const
const typeWeight vertexCount () const
const typeWeight edgeCount () const
typeWeight weighted_degree (const typeVertex &vertex) const
bool replace (const typeVertex &oldValue, const typeVertex &newValue)
const std::string toString (const StringFormatter &sf=defaultStringFormatter) const
Public Member Functions inherited from GraphInterface
virtual ~GraphInterface ()
Private Member Functions
void maxWeight (const typeWeight &weight)
void updateMaxWeight ()
void updateWeight (HalfEdge &he, const typeWeight &newWeight)
Private Attributes
typeVertexList vertices
typeLinks links
typeWeight total_weight
typeWeight max_weight
Detailed Description
Graph.
Class that implements an undirected graph. When an edge is added/removed/modified, its mirror edge is also added/removed/modified. This means that, if an edge (A,B) is added, the edge (B,A) is also added.
Author
poltergeist0
Date
2018-08-19
Definition at line 37 of file graphUndirected.h.
Constructor & Destructor Documentation
GraphUndirected() [1/2]
GraphUndirected::GraphUndirected () inline
default constructor
Definition at line 78 of file graphUndirected.h.
GraphUndirected() [2/2]
GraphUndirected::GraphUndirected (const GraphUndirected & original) inline
Copy constructor
Definition at line 83 of file graphUndirected.h.
Member Function Documentation
addEdge() [1/2]
bool GraphUndirected::addEdge (const typeVertex & source, const typeVertex & destination, const typeWeight & weight = 1.0, const bool & replace = false) inline virtual
Add an edge
Parameters
source
destination
weight Default value is one
replace if true and link exists, it replaces the weight, otherwise fails. Default value is false
Returns
true if the edge was added. False otherwise
Implements GraphInterface.
Reimplemented in GraphUndirectedGroupable.
Definition at line 96 of file graphUndirected.h.
References multimap::find(), maxWeight(), noVertex, replace(), updateMaxWeight(), updateWeight(), HalfEdge::weight(), and weight().
Referenced by GraphUndirectedGroupable::addEdge(), GraphUndirectedGroupable::communitiesToGraph(), GraphUndirectedGroupable::community(), and GraphUndirectedGroupable::removeEdge().
addEdge() [2/2]
bool GraphUndirected::addEdge (const Edge & edge, const bool & replace = false) inline virtual
See also
{addEdge(const typeVertex & source, const typeVertex & destination, const typeWeight & weight=1.0, const bool & replace=false)}
Parameters
edge
replace
Returns
Implements GraphInterface.
Reimplemented in GraphUndirectedGroupable.
Definition at line 150 of file graphUndirected.h.
References addEdge(), Edge::destination(), Edge::source(), and Edge::weight().
Referenced by addEdge().
edgeCount()
const typeWeight GraphUndirected::edgeCount () const inline virtual
Returns
the number of edges in the graph
Implements GraphInterface.
Definition at line 270 of file graphUndirected.h.
Referenced by AlgorithmLouvain::edgeCount().
edges()
typeLinksRangeConst GraphUndirected::edges () const inline virtual
Returns
a pair with iterators to the beginning and end of the edge list.
Implements GraphInterface.
Definition at line 85 of file graphUndirected.h.
Referenced by GraphUndirectedGroupable::communitiesToGraph(), and AlgorithmLouvain::edges().
getVertices()
const typeVertexList& GraphUndirected::getVertices () const inline virtual
Returns
a constant set with all vertices
Implements GraphInterface.
Definition at line 198 of file graphUndirected.h.
References vertices.
Referenced by DynCommBase::addRemoveEdges(), GraphUndirectedGroupable::communities(), DynCommBase::communityMapping(), AlgorithmLouvain::getVertices(), AlgorithmLouvain::one_level(), CriterionBalMod::quality(), CriterionModularity::quality(), and DynCommBase::vertices().
maxWeight() [1/2]
void GraphUndirected::maxWeight (const typeWeight & weight) inline private
Definition at line 49 of file graphUndirected.h.
References weight().
maxWeight() [2/2]
const typeWeight& GraphUndirected::maxWeight () const inline virtual
Returns
the largest weight of all edges in the graph
Implements GraphInterface.
Definition at line 251 of file graphUndirected.h.
References max_weight.
Referenced by addEdge(), AlgorithmLouvain::maxWeight(), and updateMaxWeight().
neighbors()
typeLinksRangeConst GraphUndirected::neighbors (const typeVertex & vertex) const inline virtual
Get the neighbors of a vertex.
The pair can change between calls if the Indexed edge list is modified.
Parameters
vertex
Returns
pointers to the first and last neighbor of the vertex
Implements GraphInterface.
Definition at line 206 of file graphUndirected.h.
References noVertex.
Referenced by GraphUndirectedGroupable::community(), AlgorithmLouvain::disband(), GraphUndirectedGroupable::neighboringCommunities(), AlgorithmLouvain::neighbors(), GraphUndirectedGroupable::neighborsCommunityCount(), GraphUndirectedGroupable::neighborsCommunityWeight(), neighborsWeight(), DynCommBase::neighbours(), toString(), and weighted_degree().
neighborsCount()
unsigned int GraphUndirected::neighborsCount (const typeVertex & vertex) const inline virtual
Get the number of neighbors of a vertex.
Parameters
vertex
Returns
the number of neighbors of the given vertex
Implements GraphInterface.
Definition at line 231 of file graphUndirected.h.
References noVertex.
Referenced by GraphUndirectedGroupable::neighboringCommunitiesCount(), AlgorithmLouvain::neighborsCount(), and GraphUndirectedGroupable::removeEdge().
neighborsWeight()
typeWeight GraphUndirected::neighborsWeight (const typeVertex & vertex) const inline virtual
Get the sum of the weights of the neighbors of a vertex.
Parameters
vertex
Returns
the sum of the weights of the neighbors of the given vertex
Implements GraphInterface.
Definition at line 216 of file graphUndirected.h.
References neighbors().
Referenced by GraphUndirectedGroupable::community(), and GraphUndirectedGroupable::neighboringCommunitiesWeight().
removeEdge() [1/2]
bool GraphUndirected::removeEdge (const typeVertex & source, const typeVertex & destination) inline virtual
remove an edge
Parameters
source
destination
Returns
true if the edge existed and was successfully removed
Implements GraphInterface.
Reimplemented in GraphUndirectedGroupable.
Definition at line 159 of file graphUndirected.h.
References multimap::find(), and updateMaxWeight().
Referenced by GraphUndirectedGroupable::communitiesToGraph(), GraphUndirectedGroupable::community(), and GraphUndirectedGroupable::removeEdge().
removeEdge() [2/2]
bool GraphUndirected::removeEdge (const Edge & edge) inline virtual
See also
{removeEdge(const typeVertex & source, const typeVertex & destination)}
Parameters
edge
Returns
Implements GraphInterface.
Reimplemented in GraphUndirectedGroupable.
Definition at line 193 of file graphUndirected.h.
References Edge::destination(), removeEdge(), and Edge::source().
Referenced by removeEdge().
replace()
bool GraphUndirected::replace (const typeVertex & oldValue, const typeVertex & newValue) inline virtual
Replace all vertex occurrences of oldValue by newValue
Parameters
oldValue
newValue
Returns
true if replacement succeeded
Implements GraphInterface.
Reimplemented in GraphUndirectedGroupable.
Definition at line 294 of file graphUndirected.h.
References multimap::find(), and noVertex.
Referenced by addEdge(), GraphUndirectedGroupable::replace(), and GraphUndirectedGroupable::replaceCommunity().
toString()
const std::string GraphUndirected::toString (const StringFormatter & sf = defaultStringFormatter) const inline virtual
Returns
a string representation of this graph
Implements GraphInterface.
Reimplemented in GraphUndirectedGroupable.
Definition at line 342 of file graphUndirected.h.
References HalfEdge::destination(), StringFormatter::end(), StringFormatter::header(), neighbors(), StringFormatter::setClose(), StringFormatter::setOpen(), StringFormatter::start(), StringFormatter::tupleClose(), StringFormatter::tupleOpen(), StringFormatter::valueSeparator(), and HalfEdge::weight().
Referenced by GraphUndirectedGroupable::toString().
totalWeight()
const typeWeight GraphUndirected::totalWeight () const inline virtual
Returns
the sum of the weight of all edges in the graph
Implements GraphInterface.
Definition at line 258 of file graphUndirected.h.
References total_weight.
Referenced by CriterionBalMod::gain(), CriterionModularity::gain(), CriterionBalMod::quality(), CriterionModularity::quality(), and AlgorithmLouvain::totalWeight().
updateMaxWeight()
void GraphUndirected::updateMaxWeight () inline private
Definition at line 56 of file graphUndirected.h.
References maxWeight(), and HalfEdge::weight().
Referenced by addEdge(), and removeEdge().
updateWeight()
void GraphUndirected::updateWeight (HalfEdge & he, const typeWeight & newWeight) inline private
Definition at line 67 of file graphUndirected.h.
References HalfEdge::weight().
Referenced by addEdge().
vertexCount()
const typeWeight GraphUndirected::vertexCount () const inline virtual
Returns
the number of vertices in the graph
Implements GraphInterface.
Definition at line 265 of file graphUndirected.h.
Referenced by GraphUndirectedGroupable::communityCount(), DynCommBase::communityMapping(), DynCommBase::vertexCount(), and AlgorithmLouvain::verticesCount().
weight()
typeWeight GraphUndirected::weight (const typeVertex & source, const typeVertex & destination) const inline virtual
Returns
the weight of the edge
Implements GraphInterface.
Definition at line 239 of file graphUndirected.h.
References multimap::find(), and HalfEdge::weight().
Referenced by addEdge(), GraphUndirectedGroupable::addEdge(), AlgorithmLouvain::addRemoveEdgePost(), AlgorithmLouvain::addRemoveEdgePre(), GraphUndirectedGroupable::communitiesToGraph(), GraphUndirectedGroupable::community(), maxWeight(), GraphUndirectedGroupable::removeEdge(), GraphUndirectedGroupable::update(), DynCommBase::weight(), and GraphUndirectedGroupable::weightCommunity().
weighted_degree()
typeWeight GraphUndirected::weighted_degree (const typeVertex & vertex) const inline virtual
Parameters
vertex
Returns
the weighted degree (sum of weights of the neighbors) of the given vertex
Implements GraphInterface.
Definition at line 276 of file graphUndirected.h.
References neighbors(), and HalfEdge::weight().
Referenced by CriterionBalMod::gain(), CriterionModularity::gain(), and AlgorithmLouvain::weighted_degree().
Member Data Documentation
links
typeLinks GraphUndirected::links private
Definition at line 40 of file graphUndirected.h.
max_weight
typeWeight GraphUndirected::max_weight private
Definition at line 43 of file graphUndirected.h.
Referenced by maxWeight().
total_weight
typeWeight GraphUndirected::total_weight private
Definition at line 42 of file graphUndirected.h.
Referenced by totalWeight().
vertices
typeVertexList GraphUndirected::vertices private
Definition at line 39 of file graphUndirected.h.
Referenced by getVertices().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/graphUndirected.h