DynComm: Louvain Class Reference
Louvain Class Reference
#include <algorithmLouvain.h>
Public Member Functions
bool addRemoveEdgePre (const typeVertex &source, const typeVertex &destination, const typeWeight &weight=1.0)
bool addRemoveEdgePost (const typeVertex &source, const typeVertex &destination, const typeWeight &weight=1.0)
bool run ()
Louvain ()=delete
~Louvain ()
Louvain (GraphUndirectedGroupable &graph, Quality &quality, ProgramParameters &algorithmParameters=argumentsDefault)
const std::string toString (const StringFormater &sf=defaultStringFormater) const
Private Member Functions
const typeCommunity & community (const typeVertex &node) const
bool community (const typeVertex &node, const typeCommunity &com)
typeWeight innerEdges (const typeCommunity &c) const
typeWeight totalEdges (const typeCommunity &c) const
typeLinksRangeConst edges () const
const typeVertexList & getVertices () const
typeCommunityListRange vertices (const typeCommunity &c)
typeLinksRangeConst neighbors (const typeVertex &node) const
unsigned int neighborsCount (const typeVertex &node) const
unsigned int neighborsCommunityCount (const typeVertex &node) const
typeWeight neighborsCommunityWeight (const typeVertex &node, const typeCommunity &com)
typeWeight neighborsCommunityWeight (const typeVertex &node)
const typeWeight & maxWeight () const
const typeWeight totalWeight () const
const typeWeight verticesCount () const
const typeWeight edgeCount () const
const typeWeight communityCount () const
typeWeight weighted_degree (const typeVertex &vertex) const
typeQuality gain (const typeVertex &vertex, const typeCommunity &comm) const
typeQuality quality () const
void disband (const typeCommunity c1, const typeCommunity c2)
std::map< typeCommunity, typeWeight > neigh_comm (const typeVertex &vertex) const
bool one_level ()
Private Member Functions inherited from AlgorithmBase
AlgorithmBase ()=delete
virtual ~AlgorithmBase ()
AlgorithmBase (GraphUndirectedGroupable &graph, const Quality &quality, const ProgramParameters &parameters=argumentsDefault)
const std::string toString (const StringFormater &sf=defaultStringFormater) const
Private Member Functions inherited from AlgorithmInterface
virtual ~AlgorithmInterface ()
Private Member Functions inherited from QualityInterface
virtual ~QualityInterface ()
Private Attributes
GraphUndirectedGroupable cg
Quality qltc
bool firstRun =true
Private Attributes inherited from AlgorithmBase
GraphUndirectedGroupable & grph
const ProgramParameters & prmtrs
const Quality & qlt
Detailed Description
Dynamic Louvain implementation
Definition at line 16 of file algorithmLouvain.h.
Constructor & Destructor Documentation
Louvain() [1/2]
Louvain::Louvain () delete
Default constructor not acceptable. Must be passed at least the graph
Referenced by run().
~Louvain()
Louvain::~Louvain () inline
Destructor
Definition at line 435 of file algorithmLouvain.h.
Louvain() [2/2]
Louvain::Louvain (GraphUndirectedGroupable & graph, Quality & quality, ProgramParameters & algorithmParameters = argumentsDefault) inline
Constructor
Definition at line 440 of file algorithmLouvain.h.
Member Function Documentation
addRemoveEdgePost()
bool Louvain::addRemoveEdgePost (const typeVertex & source, const typeVertex & destination, const typeWeight & weight = 1.0) inline virtual
Function execute after adding or removing a single edge from the graph. It is used internally by the constructor and the addRemoveEdges function. Any edge with a weight different from zero is inserted. Any edge with a weight of exactly zero is removed.
Parameters
source
destination
weight
Returns
true if adding/removing succeeded
Implements AlgorithmInterface.
Definition at line 380 of file algorithmLouvain.h.
References GraphUndirectedGroupable::addEdge(), GraphUndirectedGroupable::community(), disband(), AlgorithmBase::grph, and GraphUndirected::weight().
Referenced by Algorithm::addRemoveEdgePost().
addRemoveEdgePre()
bool Louvain::addRemoveEdgePre (const typeVertex & source, const typeVertex & destination, const typeWeight & weight = 1.0) inline virtual
Function to execute before adding or removing a single edge from the graph. It is used internally by the constructor and the addRemoveEdges function. Any edge with a weight different from zero is inserted. Any edge with a weight of exactly zero is removed.
Parameters
source
destination
weight
Returns
true if adding/removing succeeded
Implements AlgorithmInterface.
Definition at line 356 of file algorithmLouvain.h.
References GraphUndirectedGroupable::addEdge(), GraphUndirectedGroupable::community(), AlgorithmBase::grph, GraphUndirectedGroupable::removeEdge(), and GraphUndirected::weight().
Referenced by Algorithm::addRemoveEdgePre().
community() [1/2]
const typeCommunity& Louvain::community (const typeVertex & node) const inline private
Parameters
node
Returns
the community of the given node or a special community of zero if the node does not exist
Definition at line 32 of file algorithmLouvain.h.
References GraphUndirectedGroupable::community(), AlgorithmBase::grph, and noGroup.
Referenced by neigh_comm(), and one_level().
community() [2/2]
bool Louvain::community (const typeVertex & node, const typeCommunity & com) inline private
set the community of a single node or replace old community by new community on all nodes
Parameters
node is either the node to be assigned a new community or the old community depending whether replaceAll is respectively false or true
community is the new community
replaceAll if true replaces the old community indicated by parameter node by the new community, otherwise replaces the community only for the given node
Returns
true if the node exists and insertion succeeded or replacement succeeded
Definition at line 47 of file algorithmLouvain.h.
References GraphUndirectedGroupable::community(), and AlgorithmBase::grph.
communityCount()
const typeWeight Louvain::communityCount () const inline private
Definition at line 126 of file algorithmLouvain.h.
References GraphUndirectedGroupable::communityCount(), and AlgorithmBase::grph.
disband()
void Louvain::disband (const typeCommunity c1, const typeCommunity c2) inline private
Definition at line 146 of file algorithmLouvain.h.
References GraphUndirectedGroupable::addEdge(), GraphUndirectedGroupable::community(), HalfEdge::destination(), GraphUndirectedGroupable::disband(), AlgorithmBase::grph, GraphUndirectedGroupable::neighboringCommunities(), GraphUndirected::neighbors(), GraphUndirectedGroupable::removeEdge(), GraphUndirectedGroupable::vertices(), and HalfEdge::weight().
Referenced by addRemoveEdgePost().
edgeCount()
const typeWeight Louvain::edgeCount () const inline private
Definition at line 121 of file algorithmLouvain.h.
References GraphUndirected::edgeCount(), and AlgorithmBase::grph.
edges()
typeLinksRangeConst Louvain::edges () const inline private
Definition at line 66 of file algorithmLouvain.h.
References GraphUndirected::edges(), and AlgorithmBase::grph.
gain()
typeQuality Louvain::gain (const typeVertex & node, const typeCommunity & comm) const inline private virtual
compute the gain in quality by moving the given node from its current community to the given community comm
Parameters
node
comm
Returns
the gain in quality, which may be positive or negative
Implements QualityInterface.
Definition at line 136 of file algorithmLouvain.h.
References Quality::gain(), and AlgorithmBase::qlt.
Referenced by one_level().
getVertices()
const typeVertexList& Louvain::getVertices () const inline private
Definition at line 71 of file algorithmLouvain.h.
References GraphUndirected::getVertices(), and AlgorithmBase::grph.
Referenced by one_level().
innerEdges()
typeWeight Louvain::innerEdges (const typeCommunity & c) const inline private
Definition at line 56 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::innerEdges().
maxWeight()
const typeWeight& Louvain::maxWeight () const inline private
Definition at line 106 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::maxWeight().
neigh_comm()
std::map<typeCommunity, typeWeight> Louvain::neigh_comm (const typeVertex & vertex) const inline private
Definition at line 226 of file algorithmLouvain.h.
References community(), HalfEdge::destination(), neighbors(), noVertex, and HalfEdge::weight().
Referenced by one_level().
neighbors()
typeLinksRangeConst Louvain::neighbors (const typeVertex & node) const inline private
Definition at line 81 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::neighbors().
Referenced by neigh_comm(), and one_level().
neighborsCommunityCount()
unsigned int Louvain::neighborsCommunityCount (const typeVertex & node) const inline private
Definition at line 91 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::neighborsCommunityCount().
neighborsCommunityWeight() [1/2]
typeWeight Louvain::neighborsCommunityWeight (const typeVertex & node, const typeCommunity & com) inline private
Definition at line 96 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::neighborsCommunityWeight().
neighborsCommunityWeight() [2/2]
typeWeight Louvain::neighborsCommunityWeight (const typeVertex & node) inline private
Definition at line 101 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::neighborsCommunityWeight().
neighborsCount()
unsigned int Louvain::neighborsCount (const typeVertex & node) const inline private
Definition at line 86 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::neighborsCount().
one_level()
bool Louvain::one_level () inline private
Function where the actual algorithm is implemented
Definition at line 253 of file algorithmLouvain.h.
References GraphUndirectedGroupable::addEdge(), GraphUndirectedGroupable::communities(), GraphUndirectedGroupable::communitiesToGraph(), community(), GraphUndirectedGroupable::community(), HalfEdge::destination(), gain(), getVertices(), GraphUndirected::getVertices(), AlgorithmBase::grph, GraphUndirectedGroupable::innerEdges(), neigh_comm(), GraphUndirectedGroupable::neighboringCommunities(), neighbors(), ProgramParameters::precision, AlgorithmBase::prmtrs, quality(), GraphUndirectedGroupable::vertices(), and HalfEdge::weight().
Referenced by run().
quality()
typeQuality Louvain::quality () const inline private virtual
compute the quality of the current partition scheme
Returns
the quality value
Implements QualityInterface.
Definition at line 141 of file algorithmLouvain.h.
References AlgorithmBase::qlt, and Quality::quality().
Referenced by one_level().
run()
bool Louvain::run () inline virtual
Function where the actual algorithm is implemented It is called at the end of the constructor and the addRemoveEdges function.
Returns
false if an error occurred. Otherwise, true
Implements AlgorithmInterface.
Definition at line 410 of file algorithmLouvain.h.
References Louvain(), and one_level().
Referenced by Algorithm::run().
toString()
const std::string Louvain::toString (const StringFormater & sf = defaultStringFormater) const inline
Definition at line 450 of file algorithmLouvain.h.
References StringFormater::build(), StringFormater::header(), AlgorithmBase::toString(), and GraphUndirectedGroupable::toString().
Referenced by Algorithm::toString().
totalEdges()
typeWeight Louvain::totalEdges (const typeCommunity & c) const inline private
Definition at line 61 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::totalEdges().
totalWeight()
const typeWeight Louvain::totalWeight () const inline private
Definition at line 111 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::totalWeight().
vertices()
typeCommunityListRange Louvain::vertices (const typeCommunity & c) inline private
Definition at line 76 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::vertices().
verticesCount()
const typeWeight Louvain::verticesCount () const inline private
Definition at line 116 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::vertexCount().
weighted_degree()
typeWeight Louvain::weighted_degree (const typeVertex & vertex) const inline private
Definition at line 131 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::weighted_degree().
Member Data Documentation
cg
GraphUndirectedGroupable Louvain::cg private
Definition at line 18 of file algorithmLouvain.h.
firstRun
bool Louvain::firstRun =true private
On first run use the reference (g) to calculate node grouping into communities. On subsequent runs, use the cg having the nodes being the communities found in the reference
Definition at line 25 of file algorithmLouvain.h.
qltc
Quality Louvain::qltc private
Definition at line 19 of file algorithmLouvain.h.
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/algorithmLouvain.h