DynComm: CriterionInterface Class Reference
CriterionInterface Class Reference abstract
Criterion interface.
#include <criterionInterface.h>
Public Member Functions
virtual ~CriterionInterface ()
virtual typeCriterion gain (const typeVertex &vertex, const typeCommunity &comm) const =0
virtual typeCriterion quality () const =0
Detailed Description
Criterion interface.
All criterion must implement the functions defined in this class.
Also, at the end of this class, there is a comment with the skeleton of a constructor that must be defined in classes that implement this interface.
Author
poltergeist0
Date
2018-08-19
Definition at line 57 of file criterionInterface.h.
Constructor & Destructor Documentation
~CriterionInterface()
virtual CriterionInterface::~CriterionInterface () inline virtual
Definition at line 59 of file criterionInterface.h.
References gain(), and quality().
Member Function Documentation
gain()
virtual typeCriterion CriterionInterface::gain (const typeVertex & vertex, const typeCommunity & comm) const pure virtual
compute the quality obtained if the given vertex was moved from its current community to the given community
Parameters
vertex
comm new potential community for given vertex
Returns
the quality, which may be positive or negative
Implemented in Criterion, CriterionModularity, and CriterionBalMod.
Referenced by ~CriterionInterface().
quality()
virtual typeCriterion CriterionInterface::quality () const pure virtual
compute the quality of the current partition scheme
Returns
the quality value
Implemented in Criterion, CriterionModularity, and CriterionBalMod.
Referenced by ~CriterionInterface().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/criterionInterface.h