DynComm: Edge Class Reference
Edge Class Reference
Edge class.
#include <edge.h>
Public Member Functions
Edge (const typeVertex &source, const typeVertex &destination, const typeWeight &weight=0)
const typeVertex & source () const
const bool source (const typeVertex &source)
const typeVertex & destination () const
const bool destination (const typeVertex &destination)
const typeWeight & weight () const
const bool weight (const typeWeight &weight)
const bool operator< (const Edge &rhs) const
const bool operator== (const Edge &rhs) const
const bool operator== (const typeVertex &rhs) const
operator const typeVertex & () const
std::string toString (const StringFormatter &sf=defaultStringFormatter) const
Private Attributes
typeVertex src
Additional Inherited Members
Private Member Functions inherited from HalfEdge
const typeVertex & destination () const
const bool destination (const typeVertex &destination)
const typeWeight & weight () const
const bool weight (const typeWeight &weight)
HalfEdge (const typeVertex &destination, const typeWeight &weight=0)
const bool operator< (const HalfEdge &rhs) const
const bool operator== (const HalfEdge &rhs) const
const bool operator== (const typeVertex &rhs) const
operator const typeVertex & () const
std::string toString (const StringFormatter &sf=defaultStringFormatter) const
Detailed Description
Edge class.
Class that encapsulates the source vertex and a half edge as being an edge.
Author
poltergeist0
Date
2018-08-19
Definition at line 146 of file edge.h.
Constructor & Destructor Documentation
Edge()
Edge::Edge (const typeVertex & source, const typeVertex & destination, const typeWeight & weight = 0) inline
Constructor with a weight of zero as default
Parameters
source
destination
weight
Definition at line 157 of file edge.h.
Member Function Documentation
destination() [1/2]
const typeVertex& Edge::destination () const inline
Returns
the destination
Definition at line 177 of file edge.h.
References HalfEdge::destination().
Referenced by GraphUndirected::addEdge(), GraphUndirectedGroupable::addEdge(), Algorithm::addRemoveEdges(), GraphUndirected::removeEdge(), and GraphUndirectedGroupable::removeEdge().
destination() [2/2]
const bool Edge::destination (const typeVertex & destination) inline
Modify the destination
Parameters
destination
Returns
true if the value was modified successfully
Definition at line 183 of file edge.h.
References HalfEdge::destination().
operator const typeVertex &()
Edge::operator const typeVertex & () const inline
Assignment operator to source vertex only. Weight is ignored. Assigns the source portion to a vertex.
Returns
the source vertex of this edge
Definition at line 240 of file edge.h.
operator<()
const bool Edge::operator< (const Edge & rhs) const inline
Weak comparator for ordering. Weight is ignored
Parameters
rhs is another edge to compare to
Returns
true if this edge (first source then destination) is smaller than the given (rhs) edge (first source then destination)
Definition at line 207 of file edge.h.
References HalfEdge::operator<(), and src.
operator==() [1/2]
const bool Edge::operator== (const Edge & rhs) const inline
Comparison operator. Weight is ignored
Parameters
rhs
Returns
true if this edge (first source then destination) is equal to the given (rhs) edge (first source then destination)
Definition at line 221 of file edge.h.
References HalfEdge::operator==(), and src.
operator==() [2/2]
const bool Edge::operator== (const typeVertex & rhs) const inline
Comparison operator against source vertex only. Weight is ignored
Parameters
rhs is the vertex used to compare to
Returns
true if the source vertex of this edge is equal to the given vertex
Definition at line 231 of file edge.h.
source() [1/2]
const typeVertex& Edge::source () const inline
Returns
the source
Definition at line 163 of file edge.h.
Referenced by GraphUndirected::addEdge(), GraphUndirectedGroupable::addEdge(), Algorithm::addRemoveEdges(), GraphUndirected::removeEdge(), and GraphUndirectedGroupable::removeEdge().
source() [2/2]
const bool Edge::source (const typeVertex & source) inline
Modify the source
Parameters
source
Returns
true if the value was modified successfully
Definition at line 169 of file edge.h.
toString()
std::string Edge::toString (const StringFormatter & sf = defaultStringFormatter) const inline
Returns
a string representation of this half edge
Definition at line 246 of file edge.h.
References HalfEdge::toString().
weight() [1/2]
const typeWeight& Edge::weight () const inline
Returns
the weight of the edge
Definition at line 191 of file edge.h.
References HalfEdge::weight().
Referenced by GraphUndirected::addEdge(), GraphUndirectedGroupable::addEdge(), and Algorithm::addRemoveEdges().
weight() [2/2]
const bool Edge::weight (const typeWeight & weight) inline
Modify the weight of the edge
Parameters
weight
Returns
true if the value was modified successfully
Definition at line 197 of file edge.h.
References HalfEdge::weight().
Member Data Documentation
src
typeVertex Edge::src private
Definition at line 148 of file edge.h.
Referenced by operator<(), and operator==().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/edge.h