DynComm: WriterStream Class Reference
WriterStream Class Reference
Writer to generic output stream.
#include <writer.h>
Public Member Functions
WriterStream (std::ostream &stream, const ProgramParameters &parameters)
~WriterStream ()
bool isReady ()
bool write (const std::string &object, const WRITETYPE &type=WRITETYPE::VALUE)
Write a certain type of object to stream.
std::string status ()
Public Member Functions inherited from WriterInterface
virtual ~WriterInterface ()
Private Attributes
std::ostream & str
std::string stts
const ProgramParameters & par
unsigned int lineNumber =1
int state =0
Additional Inherited Members
Public Types inherited from WriterInterface
enum WRITETYPE : unsigned int { WRITETYPE::LINE =1, WRITETYPE::VALUE, WRITETYPE::COMMENT }
Detailed Description
Writer to generic output stream.
This writer can not write backwards, only append to the end.
Author
poltergeist0
Date
2019-02-06
Definition at line 77 of file writer.h.
Constructor & Destructor Documentation
WriterStream()
WriterStream::WriterStream (std::ostream & stream, const ProgramParameters & parameters) inline
Definition at line 86 of file writer.h.
~WriterStream()
WriterStream::~WriterStream () inline
Definition at line 88 of file writer.h.
Member Function Documentation
isReady()
bool WriterStream::isReady () inline virtual
Returns
true if the sink is ready to be written
Implements WriterInterface.
Definition at line 90 of file writer.h.
Referenced by WriterFile::isReady().
status()
std::string WriterStream::status () inline virtual
Returns
either an ok message or an error message
Implements WriterInterface.
Definition at line 144 of file writer.h.
Referenced by WriterFile::status().
write()
bool WriterStream::write (const std::string & object, const WRITETYPE & type = WRITETYPE::VALUE) inline virtual
Write a certain type of object to stream.
The type parameter defines the type of object being written. This is used to automatically add carriage returns, value separators and prepare writing of the next object type.
Parameters
type defines what is being written
Returns
true if writing succeeded
Implements WriterInterface.
Definition at line 105 of file writer.h.
References WriterInterface::COMMENT, WriterInterface::LINE, and WriterInterface::VALUE.
Referenced by WriterFile::write().
Member Data Documentation
lineNumber
unsigned int WriterStream::lineNumber =1 private
Definition at line 82 of file writer.h.
par
const ProgramParameters& WriterStream::par private
Definition at line 81 of file writer.h.
state
int WriterStream::state =0 private
Definition at line 83 of file writer.h.
str
std::ostream& WriterStream::str private
Definition at line 79 of file writer.h.
stts
std::string WriterStream::stts private
Definition at line 80 of file writer.h.
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/writer.h