DynComm: Algorithm Class Reference
Algorithm Class Reference
Aggregator class for all main algorithms.
#include <algorithm.h>
Public Types
enum ALGORITHM : unsigned int { ALGORITHM::LOUVAIN =1, ALGORITHM::SHAKEN }
Public Member Functions
Algorithm ()=delete
Algorithm (GraphUndirectedGroupable &grph, Criterion &quality, ALGORITHM algorithm=ALGORITHM::LOUVAIN, ProgramParameters &algorithmParameters=argumentsDefault)
bool addRemoveEdges (ReaderInterface< Edge > *reader)
const std::string toString (const StringFormatter &sf=defaultStringFormatter) const
Private Member Functions
bool addRemoveEdgePre (const typeVertex &source, const typeVertex &destination, const typeWeight &weight=1.0)
bool addRemoveEdgePost (const typeVertex &source, const typeVertex &destination, const typeWeight &weight=1.0)
bool run ()
Private Member Functions inherited from AlgorithmBase
AlgorithmBase ()=delete
virtual ~AlgorithmBase ()
AlgorithmBase (GraphUndirectedGroupable &graph, const Criterion &quality, const ProgramParameters &parameters=argumentsDefault)
const std::string toString (const StringFormatter &sf=defaultStringFormatter) const
Private Member Functions inherited from AlgorithmInterface
virtual ~AlgorithmInterface ()
Private Attributes
const ALGORITHM algrthm
AlgorithmLouvain algorithmLouvain
Private Attributes inherited from AlgorithmBase
GraphUndirectedGroupable & grph
const ProgramParameters & prmtrs
const Criterion & qlt
Detailed Description
Aggregator class for all main algorithms.
It is a simple class that only instantiates all algorithms and dispatches function calls to the correct one.
Author
poltergeist0
Date
2019-01-01
Definition at line 63 of file algorithm.h.
Member Enumeration Documentation
ALGORITHM
enum Algorithm::ALGORITHM : unsigned int strong
Enumeration with the list of supported Dynamic Communities algorithms. This enumeration must start at 1 since this code is used in R and R indexing (for arrays, etc) starts at 1 instead of 0. Otherwise C++ would assign the first algorithm a 0.
Enumerator
LOUVAIN
SHAKEN
Definition at line 76 of file algorithm.h.
Constructor & Destructor Documentation
Algorithm() [1/2]
Algorithm::Algorithm () delete
Default constructor not acceptable. Must be passed at least the chosen algorithm and the graph
Referenced by run().
Algorithm() [2/2]
Algorithm::Algorithm (GraphUndirectedGroupable & grph, Criterion & quality, ALGORITHM algorithm = ALGORITHM::LOUVAIN, ProgramParameters & algorithmParameters = argumentsDefault) inline
Constructor.
Parameters
graph reference to the graph object
quality reference to the quality object
algorithmParameters reference to the parameters object
Definition at line 196 of file algorithm.h.
Member Function Documentation
addRemoveEdgePost()
bool Algorithm::addRemoveEdgePost (const typeVertex & source, const typeVertex & destination, const typeWeight & weight = 1.0) inline private virtual
Function execute after adding or removing a single edge from the graph. It is used internally by the addRemoveEdges function. Useful if post-processing is required, for example, to update some of variables after the edge has be added or removed. Any edge with a weight different from zero is inserted. Any edge with a weight of exactly zero is removed. Redirects call to algorithm variable.
Parameters
source source vertex
destination destination vertex
weight optional if adding an edge. Must be exactly zero to remove an edge.
Returns
true if all operations succeeded. False, otherwise.
Implements AlgorithmInterface.
Definition at line 141 of file algorithm.h.
References AlgorithmLouvain::addRemoveEdgePost(), and LOUVAIN.
Referenced by addRemoveEdges().
addRemoveEdgePre()
bool Algorithm::addRemoveEdgePre (const typeVertex & source, const typeVertex & destination, const typeWeight & weight = 1.0) inline private virtual
Function to execute before adding or removing a single edge from the graph. It is used internally by the addRemoveEdges function. Useful if pre-processing is required, for example, to update some of variables before the edge can be added or removed. Any edge with a weight different from zero is inserted. Any edge with a weight of exactly zero is removed. Redirects call to algorithm variable.
Parameters
source source vertex
destination destination vertex
weight optional if adding an edge. Must be exactly zero to remove an edge.
Returns
true if all operations succeeded. False, otherwise.
Implements AlgorithmInterface.
Definition at line 110 of file algorithm.h.
References AlgorithmLouvain::addRemoveEdgePre(), and LOUVAIN.
Referenced by addRemoveEdges().
addRemoveEdges()
bool Algorithm::addRemoveEdges (ReaderInterface< Edge > * reader) inline
Function to add and remove edges from the graph. Any edge with a weight different from zero is inserted. Any edge with a weight of exactly zero is removed.
Parameters
reader is a Reader object that is responsible for converting the required data from its original format to Edges
Returns
true if adding/removing succeeded
Definition at line 223 of file algorithm.h.
References GraphUndirectedGroupable::addEdge(), addRemoveEdgePost(), addRemoveEdgePre(), Edge::destination(), AlgorithmBase::grph, ReaderInterface< TYPERETURN >::hasNext(), ReaderInterface< TYPERETURN >::next(), GraphUndirectedGroupable::removeEdge(), run(), Edge::source(), and Edge::weight().
Referenced by DynCommBase::addRemoveEdges().
run()
bool Algorithm::run () inline private virtual
Function where the actual algorithms are implemented. It is called at the end of the addRemoveEdges function. Redirects call to algorithm variable.
Returns
true if all operations succeeded. False, otherwise.
Implements AlgorithmInterface.
Definition at line 165 of file algorithm.h.
References Algorithm(), LOUVAIN, and AlgorithmLouvain::run().
Referenced by addRemoveEdges().
toString()
const std::string Algorithm::toString (const StringFormatter & sf = defaultStringFormatter) const inline
Function that converts this object to a string representation. Might be useful for debugging.
Parameters
sf is a StringFormater object that facilitates formating
Returns
the string representing this object
Definition at line 254 of file algorithm.h.
References LOUVAIN, and AlgorithmLouvain::toString().
Member Data Documentation
algorithmLouvain
AlgorithmLouvain Algorithm::algorithmLouvain private
Definition at line 87 of file algorithm.h.
algrthm
const ALGORITHM Algorithm::algrthm private
Definition at line 82 of file algorithm.h.
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/algorithm.h