DynComm: GraphUndirectedGroupable Class Reference
GraphUndirectedGroupable Class Reference
Groupable Undirected Graph.
#include <graphUndirectedGroupable.h>
Public Member Functions
bool addEdge (const typeVertex &source, const typeVertex &destination, const typeWeight &weight=1.0, const bool &replace=false)
bool addEdge (const Edge &edge, const bool &replace=false)
bool replace (const typeVertex &oldValue, const typeVertex &newValue)
bool removeEdge (const typeVertex &source, const typeVertex &destination)
bool removeEdge (const Edge &edge)
typeCommunityListRange vertices (const typeCommunity &c) const
void disband (const typeCommunity &c, const unsigned int &level=0)
Disband the given community.
const typeCommunities communities () const
const typeWeight communityCount () const
const typeCommunity & community (const typeVertex &vertex) const
bool replaceCommunity (const typeCommunity &old, const typeCommunity &com)
bool community (const typeVertex &vertex, const typeCommunity &com)
typeWeight innerEdges (const typeCommunity &c) const
typeWeight totalEdges (const typeCommunity &c) const
typeLinksRangeConst neighbouringCommunities (const typeCommunity &com) const
typeWeight neighbouringCommunitiesWeight (const typeCommunity &com) const
unsigned int neighbouringCommunitiesCount (const typeCommunity &com) const
typeWeight weightCommunity (const typeCommunity &source, const typeCommunity &destination) const
unsigned int neighboursCommunityCount (const typeVertex &vertex) const
typeWeight neighboursCommunityWeight (const typeVertex &vertex, const typeCommunity &com) const
typeWeight neighboursCommunityWeight (const typeVertex &vertex) const
bool communitiesToGraph ()
Populate the graph with the current community to community mapping.
const std::string toString (const StringFormatter &sf=defaultStringFormatter) const
Public Member Functions inherited from GraphUndirected
GraphUndirected ()
GraphUndirected (const GraphUndirected &original)
typeLinksRangeConst edges () const
const typeVertexList & getVertices () const
typeLinksRangeConst neighbours (const typeVertex &vertex) const
Get the neighbours of a vertex.
typeWeight neighboursWeight (const typeVertex &vertex) const
Get the sum of the weights of the neighbours of a vertex.
unsigned int neighboursCount (const typeVertex &vertex) const
Get the number of neighbours of a vertex.
typeWeight weight (const typeVertex &source, const typeVertex &destination) const
const typeWeight & maxWeight () const
const typeWeight totalWeight () const
const typeWeight vertexCount () const
const typeWeight edgeCount () const
typeWeight weighted_degree (const typeVertex &vertex) const
Public Member Functions inherited from GraphInterface
virtual ~GraphInterface ()
Private Member Functions
typeVertex minimumNode (const typeCommunity &com)
bool update (typeCommunityEdges &ce, const typeCommunity &com, const typeWeight &weight, const bool &add=true)
bool replace (typeCommunityEdges &ce, const typeCommunity &old, const typeCommunity &com)
Private Attributes
typeCommunityList n2c
typeCommunityEdges inner
typeCommunityEdges total
GraphUndirected cc
Detailed Description
Groupable Undirected Graph.
Class that implements a groupable undirected graph. When an edge is added/removed/modified, its mirror edge is also added/removed/modified. This means that, if an edge (A,B) is added, the edge (B,A) is also added. Also, vertices can be individually assigned to groups and, those groups, form an higher level view of the graph, being itself a graph with edges and weights where the groups are vertices.
of a graph:
lower level: vertices: 1,2,3,4,5,6 edges: (1,2),(1,3),(2,3),(3,4),(4,5),(4,6),(5,6) communities(vertex,community):(1,1),(2,1),(3,1),(4,4),(5,4),(6,4) higher level: vertices: 1,4 edges: (1,4) communities(vertex,community):(1,1),(4,1)
Author
poltergeist0
Date
2018-08-19
Definition at line 157 of file graphUndirectedGroupable.h.
Member Function Documentation
addEdge() [1/2]
bool GraphUndirectedGroupable::addEdge (const typeVertex & source, const typeVertex & destination, const typeWeight & weight = 1.0, const bool & replace = false) inline virtual
Add an edge
Parameters
source
destination
weight Default value is one
replace if true and link exists, it replaces the weight, otherwise fails. Default value is false
Returns
true if the edge was added. False otherwise
Reimplemented from GraphUndirected.
Definition at line 269 of file graphUndirectedGroupable.h.
References MapReversable< T, U >::add(), GraphUndirected::addEdge(), community(), noGroup, replace(), update(), and GraphUndirected::weight().
Referenced by AlgorithmLouvain::addRemoveEdgePost(), AlgorithmLouvain::addRemoveEdgePre(), Algorithm::addRemoveEdges(), AlgorithmLouvain::disband(), and AlgorithmLouvain::one_level().
addEdge() [2/2]
bool GraphUndirectedGroupable::addEdge (const Edge & edge, const bool & replace = false) inline virtual
Add an edge
Parameters
edge
replace if true and link exists, it replaces the weight, otherwise fails. Default value is false
Returns
true if the edge was added. False otherwise
Reimplemented from GraphUndirected.
Definition at line 322 of file graphUndirectedGroupable.h.
References addEdge(), Edge::destination(), replace(), Edge::source(), and Edge::weight().
Referenced by addEdge().
communities()
const typeCommunities GraphUndirectedGroupable::communities () const inline
Returns
the list of all existing communities
Definition at line 429 of file graphUndirectedGroupable.h.
References GraphUndirected::getVertices().
Referenced by DynCommBase::communities(), DynCommBase::communityMapping(), and AlgorithmLouvain::one_level().
communitiesToGraph()
bool GraphUndirectedGroupable::communitiesToGraph () inline
Populate the graph with the current community to community mapping.
When vertices (lower level view) are merged into communities (higher level view) and there is an interest to save only the higher level view, this function can be called to perform that action.
Definition at line 716 of file graphUndirectedGroupable.h.
References GraphUndirected::addEdge(), MapReversable< T, U >::cbegin(), MapReversable< T, U >::cend(), community(), GraphUndirected::edges(), MapReversable< T, U >::remove(), GraphUndirected::removeEdge(), GraphUndirected::weight(), and weightCommunity().
Referenced by AlgorithmLouvain::one_level().
community() [1/2]
const typeCommunity& GraphUndirectedGroupable::community (const typeVertex & vertex) const inline
Parameters
node
Returns
the community of the given vertex or a special community of noGRoup if the vertex does not exist
Definition at line 447 of file graphUndirectedGroupable.h.
References MapReversable< T, U >::cend(), MapReversable< T, U >::find(), and noGroup.
Referenced by addEdge(), AlgorithmLouvain::addRemoveEdgePost(), AlgorithmLouvain::addRemoveEdgePre(), DynCommBase::addRemoveEdges(), communitiesToGraph(), AlgorithmLouvain::community(), DynCommBase::community(), community(), DynCommBase::communityMapping(), AlgorithmLouvain::disband(), disband(), CriterionBalMod::gain(), CriterionModularity::gain(), neighboursCommunityCount(), neighboursCommunityWeight(), AlgorithmLouvain::one_level(), and removeEdge().
community() [2/2]
bool GraphUndirectedGroupable::community (const typeVertex & vertex, const typeCommunity & com) inline
set the community of a single vertex
Parameters
vertex is the vertex to be assigned a new community
community is the new community
Returns
true if the node was already in the requested community or, the node exists and insertion succeeded
Definition at line 481 of file graphUndirectedGroupable.h.
References MapReversable< T, U >::add(), GraphUndirected::addEdge(), community(), HalfEdge::destination(), MapReversable< T, U >::keys(), minimumNode(), GraphUndirected::neighbours(), neighboursCommunityWeight(), GraphUndirected::neighboursWeight(), noGroup, noVertex, GraphUndirected::removeEdge(), replaceCommunity(), update(), HalfEdge::weight(), and GraphUndirected::weight().
communityCount()
const typeWeight GraphUndirectedGroupable::communityCount () const inline
Returns
the number of existing communities
Definition at line 440 of file graphUndirectedGroupable.h.
References GraphUndirected::vertexCount().
Referenced by DynCommBase::communityCount(), and AlgorithmLouvain::communityCount().
disband()
void GraphUndirectedGroupable::disband (const typeCommunity & c, const unsigned int & level = 0) inline
Disband the given community.
Disbanding takes all vertices of a community and turns them into individual communities. Since the name of a community will match the name of a vertex, the given community becomes a community of a single vertex.
Parameters
c
level
Definition at line 412 of file graphUndirectedGroupable.h.
References community(), and MapReversable< T, U >::keys().
Referenced by AlgorithmLouvain::disband().
innerEdges()
typeWeight GraphUndirectedGroupable::innerEdges (const typeCommunity & c) const inline
Get the sum of the weights of all edges of the given community where both vertices of an edge belong to the given community.
Parameters
c
Returns
the sum of the weights of all inner edges
Definition at line 560 of file graphUndirectedGroupable.h.
Referenced by DynCommBase::communityInnerEdgesWeight(), AlgorithmLouvain::innerEdges(), AlgorithmLouvain::one_level(), CriterionBalMod::quality(), and CriterionModularity::quality().
minimumNode()
typeVertex GraphUndirectedGroupable::minimumNode (const typeCommunity & com) inline private
Parameters
com
Returns
the smallest number used as a vertex in the given community
Definition at line 188 of file graphUndirectedGroupable.h.
References MapReversable< T, U >::keys(), and noVertex.
Referenced by community().
neighbouringCommunities()
typeLinksRangeConst GraphUndirectedGroupable::neighbouringCommunities (const typeCommunity & com) const inline
Get the communities that are neighbours of the given community
Parameters
com
Returns
the neighbouring communities
Definition at line 590 of file graphUndirectedGroupable.h.
References GraphUndirected::neighbours().
Referenced by DynCommBase::communityNeighbours(), AlgorithmLouvain::disband(), and AlgorithmLouvain::one_level().
neighbouringCommunitiesCount()
unsigned int GraphUndirectedGroupable::neighbouringCommunitiesCount (const typeCommunity & com) const inline
Get the number of communities that are neighbours of the given community
Parameters
com
Returns
the number of neighbouring communities
Definition at line 610 of file graphUndirectedGroupable.h.
References GraphUndirected::neighboursCount().
neighbouringCommunitiesWeight()
typeWeight GraphUndirectedGroupable::neighbouringCommunitiesWeight (const typeCommunity & com) const inline
Get the sum of the weights of the communities that are neighbours of the given community
Parameters
com
Returns
the sum of the weights of neighbouring communities
Definition at line 600 of file graphUndirectedGroupable.h.
References GraphUndirected::neighboursWeight().
neighboursCommunityCount()
unsigned int GraphUndirectedGroupable::neighboursCommunityCount (const typeVertex & vertex) const inline
Get the number of neighbours of the given vertex that belong to the same community as the vertex
Parameters
vertex
Returns
the number of neighbours
Definition at line 637 of file graphUndirectedGroupable.h.
References community(), HalfEdge::destination(), and GraphUndirected::neighbours().
Referenced by AlgorithmLouvain::neighboursCommunityCount().
neighboursCommunityWeight() [1/2]
typeWeight GraphUndirectedGroupable::neighboursCommunityWeight (const typeVertex & vertex, const typeCommunity & com) const inline
Get the sum of the weight of the neighbours of the given vertex that belong to the given community
Parameters
vertex
com is the target community
Returns
the sum of the weight of the neighbours
Definition at line 657 of file graphUndirectedGroupable.h.
References community(), HalfEdge::destination(), GraphUndirected::neighbours(), and HalfEdge::weight().
Referenced by community(), CriterionBalMod::gain(), CriterionModularity::gain(), AlgorithmLouvain::neighboursCommunityWeight(), and neighboursCommunityWeight().
neighboursCommunityWeight() [2/2]
typeWeight GraphUndirectedGroupable::neighboursCommunityWeight (const typeVertex & vertex) const inline
Get the sum of the weight of the neighbours of the given vertex that belong to the same community as the vertex
Parameters
vertex
Returns
the sum of the weight of the neighbours
Definition at line 680 of file graphUndirectedGroupable.h.
References community(), and neighboursCommunityWeight().
removeEdge() [1/2]
bool GraphUndirectedGroupable::removeEdge (const typeVertex & source, const typeVertex & destination) inline virtual
remove an edge
Parameters
source
destination
Returns
true if the edge existed and was successfully removed
Reimplemented from GraphUndirected.
Definition at line 356 of file graphUndirectedGroupable.h.
References GraphUndirected::addEdge(), community(), GraphUndirected::neighboursCount(), MapReversable< T, U >::remove(), GraphUndirected::removeEdge(), update(), and GraphUndirected::weight().
Referenced by AlgorithmLouvain::addRemoveEdgePre(), Algorithm::addRemoveEdges(), and AlgorithmLouvain::disband().
removeEdge() [2/2]
bool GraphUndirectedGroupable::removeEdge (const Edge & edge) inline virtual
See also
{removeEdge(const typeVertex & source, const typeVertex & destination)}
Parameters
edge
Returns
Reimplemented from GraphUndirected.
Definition at line 391 of file graphUndirectedGroupable.h.
References Edge::destination(), removeEdge(), and Edge::source().
Referenced by removeEdge().
replace() [1/2]
bool GraphUndirectedGroupable::replace (typeCommunityEdges & ce, const typeCommunity & old, const typeCommunity & com) inline private
Replace the name of a community
Parameters
ce is the list of communities
old is the old community name
com is the new community name
Returns
true if old community existed and replacement succeeded. False if old community did not exist
Definition at line 247 of file graphUndirectedGroupable.h.
Referenced by addEdge(), and replaceCommunity().
replace() [2/2]
bool GraphUndirectedGroupable::replace (const typeVertex & oldValue, const typeVertex & newValue) inline virtual
Replace all vertex occurrences of oldValue by newValue
Parameters
oldValue
newValue
Returns
true if replacement succeeded
Reimplemented from GraphUndirected.
Definition at line 331 of file graphUndirectedGroupable.h.
References MapReversable< T, U >::cend(), MapReversable< T, U >::replace(), GraphUndirected::replace(), MapReversable< T, U >::replaceKey(), and MapReversable< T, U >::value().
replaceCommunity()
bool GraphUndirectedGroupable::replaceCommunity (const typeCommunity & old, const typeCommunity & com) inline
replace old community by new community on all vertices
Parameters
old is the old community
comm is the new community
Returns
true if the replacement succeeded
Definition at line 462 of file graphUndirectedGroupable.h.
References noGroup, MapReversable< T, U >::replace(), replace(), and GraphUndirected::replace().
Referenced by community().
toString()
const std::string GraphUndirectedGroupable::toString (const StringFormatter & sf = defaultStringFormatter) const inline virtual
Returns
a string representation of this graph
Reimplemented from GraphUndirected.
Definition at line 782 of file graphUndirectedGroupable.h.
References StringFormatter::build(), StringFormatter::header(), map::toString(), MapReversable< T, U >::toString(), and GraphUndirected::toString().
Referenced by AlgorithmBase::toString(), and AlgorithmLouvain::toString().
totalEdges()
typeWeight GraphUndirectedGroupable::totalEdges (const typeCommunity & c) const inline
Get the sum of the weights of all edges of the given community.
Parameters
c
Returns
the sum of the weights of all edges
Definition at line 575 of file graphUndirectedGroupable.h.
Referenced by DynCommBase::communityTotalWeight(), CriterionBalMod::gain(), CriterionModularity::gain(), CriterionBalMod::quality(), CriterionModularity::quality(), and AlgorithmLouvain::totalEdges().
update()
bool GraphUndirectedGroupable::update (typeCommunityEdges & ce, const typeCommunity & com, const typeWeight & weight, const bool & add = true) inline private
Update the weight of a community
Parameters
ce is the list of communities
com is the community to update
weight is the weight to add or update
add if true adds the given weight to the existing value. Otherwise, assigns the given weight
Returns
true if an update occurred. False if it was erased or does not exist
Definition at line 214 of file graphUndirectedGroupable.h.
References GraphUndirected::weight().
Referenced by addEdge(), community(), and removeEdge().
vertices()
typeCommunityListRange GraphUndirectedGroupable::vertices (const typeCommunity & c) const inline
Parameters
c
Returns
the list of vertices of the given community
Definition at line 398 of file graphUndirectedGroupable.h.
References MapReversable< T, U >::keys().
Referenced by DynCommBase::communityVertexCount(), AlgorithmLouvain::disband(), AlgorithmLouvain::one_level(), AlgorithmLouvain::vertices(), and DynCommBase::vertices().
weightCommunity()
typeWeight GraphUndirectedGroupable::weightCommunity (const typeCommunity & source, const typeCommunity & destination) const inline
Get the weight of the edge form by two communities
Parameters
source community
destination community
Returns
the weight of the edge
Definition at line 621 of file graphUndirectedGroupable.h.
References GraphUndirected::weight().
Referenced by communitiesToGraph(), and DynCommBase::communityEdgeWeight().
Member Data Documentation
cc
GraphUndirected GraphUndirectedGroupable::cc private
Definition at line 178 of file graphUndirectedGroupable.h.
inner
typeCommunityEdges GraphUndirectedGroupable::inner private
Definition at line 167 of file graphUndirectedGroupable.h.
n2c
typeCommunityList GraphUndirectedGroupable::n2c private
Definition at line 162 of file graphUndirectedGroupable.h.
total
typeCommunityEdges GraphUndirectedGroupable::total private
Definition at line 173 of file graphUndirectedGroupable.h.
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/graphUndirectedGroupable.h