DynComm: DynCommBaseInterface Class Reference
DynCommBaseInterface Class Reference abstract
Interface for DynComm.
#include <DynCommBaseInterface.h>
Public Member Functions
virtual ~DynCommBaseInterface ()
virtual bool addRemoveEdges (ReaderEdgeBase *reader)=0
virtual typeCriterion quality () const =0
virtual int communityCount () const =0
virtual typeCommunities communities () const =0
virtual typeLinksRangeConst communityNeighbours (typeCommunity community) const =0
virtual typeWeight communityInnerEdgesWeight (typeCommunity community) const =0
virtual typeWeight communityTotalWeight (typeCommunity community) const =0
virtual typeWeight communityEdgeWeight (typeCommunity source, typeCommunity destination) const =0
virtual int communityVertexCount (typeCommunity community) const =0
virtual typeCommunity community (typeVertex vertex) const =0
virtual unsigned int vertexCount () const =0
virtual typeVertexList vertices () const =0
virtual typeVertexList vertices (typeCommunity community) const =0
virtual bool communityMapping (WriterInterface *writer, bool communityFirst=true, bool differential=true) const =0
virtual typeLinksRangeConst neighbours (typeVertex vertex) const =0
virtual typeWeight weight (const typeVertex &source, const typeVertex &destination) const =0
virtual uint64 time (bool accumulated=true) const =0
Detailed Description
Interface for DynComm.
Class that defines the interface for DynComm as seen by the user.
It has as base the interface of classes graph, criterion and algorithm.
Author
poltergeist0
Date
2019-01-01
Definition at line 39 of file DynCommBaseInterface.h.
Constructor & Destructor Documentation
~DynCommBaseInterface()
virtual DynCommBaseInterface::~DynCommBaseInterface () inline virtual
Destructor
Definition at line 44 of file DynCommBaseInterface.h.
References addRemoveEdges(), communities(), community(), communityCount(), communityEdgeWeight(), communityInnerEdgesWeight(), communityMapping(), communityNeighbours(), communityTotalWeight(), communityVertexCount(), neighbours(), quality(), time(), vertexCount(), vertices(), and weight().
Member Function Documentation
addRemoveEdges()
virtual bool DynCommBaseInterface::addRemoveEdges (ReaderEdgeBase * reader) pure virtual
Function to add and remove edges from the graph. Any edge with a weight different from zero is inserted. Any edge with a weight of exactly zero is removed.
Parameters
reader is a Reader object that is responsible for converting the required data from its original format to Edges
Returns
true if adding/removing succeeded
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
communities()
virtual typeCommunities DynCommBaseInterface::communities () const pure virtual
Returns
the list of all existing communities without any further information
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
community()
virtual typeCommunity DynCommBaseInterface::community (typeVertex vertex) const pure virtual
Parameters
vertex
Returns
the community of a given vertex
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
communityCount()
virtual int DynCommBaseInterface::communityCount () const pure virtual
Returns
the number of communities
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
communityEdgeWeight()
virtual typeWeight DynCommBaseInterface::communityEdgeWeight (typeCommunity source, typeCommunity destination) const pure virtual
Parameters
source
destination
Returns
the weight of the edge that connects two given communities
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
communityInnerEdgesWeight()
virtual typeWeight DynCommBaseInterface::communityInnerEdgesWeight (typeCommunity community) const pure virtual
Parameters
community
Returns
the sum of the weights of all inner edges of the selected community
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
communityMapping()
virtual bool DynCommBaseInterface::communityMapping (WriterInterface * writer, bool communityFirst = true, bool differential = true) const pure virtual
Get a snapshot of the current community mapping. If communityFirst is true the result will be one community per line with each line being a community followed by a list of vertices. If false, the result will be a vertex per line with each line being a single vertex and a single community. The differential parameter will probably be moved inside the writer as a parameter
Parameters
writer
communityFirst if true returns a community followed by a list of vertices, otherwise a vertex and its community
differential return only what changed in the last iteration of the algorithm
Returns
true if the operation succeeded
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
communityNeighbours()
virtual typeLinksRangeConst DynCommBaseInterface::communityNeighbours (typeCommunity community) const pure virtual
Parameters
community
Returns
the neighboring communities of the given community
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
communityTotalWeight()
virtual typeWeight DynCommBaseInterface::communityTotalWeight (typeCommunity community) const pure virtual
Parameters
community
Returns
the sum of the weights of all edges of the selected community
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
communityVertexCount()
virtual int DynCommBaseInterface::communityVertexCount (typeCommunity community) const pure virtual
Parameters
community
Returns
the amount of vertices in the selected community
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
neighbours()
virtual typeLinksRangeConst DynCommBaseInterface::neighbours (typeVertex vertex) const pure virtual
Returns
pointers to the first and last neighbor of the vertex
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
quality()
virtual typeCriterion DynCommBaseInterface::quality () const pure virtual
compute the quality of the current partition scheme
Returns
the quality value
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
time()
virtual uint64 DynCommBaseInterface::time (bool accumulated = true) const pure virtual
Returns
the time spent on processing
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
vertexCount()
virtual unsigned int DynCommBaseInterface::vertexCount () const pure virtual
Returns
the number of existing vertices
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
vertices() [1/2]
virtual typeVertexList DynCommBaseInterface::vertices () const pure virtual
Returns
the list of all existing vertices
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
vertices() [2/2]
virtual typeVertexList DynCommBaseInterface::vertices (typeCommunity community) const pure virtual
Returns
a list of all vertices belonging to the given community
Implemented in DynCommBase.
weight()
virtual typeWeight DynCommBaseInterface::weight (const typeVertex & source, const typeVertex & destination) const pure virtual
Returns
the weight of an edge
Implemented in DynCommBase.
Referenced by ~DynCommBaseInterface().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/DynCommBaseInterface.h