DynComm: Quality Class Reference
Quality Class Reference
#include <quality.h>
Public Types
enum QUALITY : unsigned int { QUALITY::MODULARITY =1, QUALITY::BALMOD }
Public Member Functions
Quality (GraphUndirectedGroupable &graph, const QUALITY &qual, const ProgramParameters &parameters=argumentsDefault)
~Quality ()
typeQuality gain (const typeVertex &node, const typeCommunity &comm) const
typeQuality quality () const
QUALITY type () const
Public Member Functions inherited from QualityInterface
virtual ~QualityInterface ()
Private Attributes
const QUALITY q
Modularity mod
BalMod bal
Detailed Description
Quality dispatcher class
Definition at line 17 of file quality.h.
Member Enumeration Documentation
QUALITY
enum Quality::QUALITY : unsigned int strong
Enumerator
MODULARITY
BALMOD
Definition at line 20 of file quality.h.
Constructor & Destructor Documentation
Quality()
Quality::Quality (GraphUndirectedGroupable & graph, const QUALITY & qual, const ProgramParameters & parameters = argumentsDefault) inline
Definition at line 30 of file quality.h.
~Quality()
Quality::~Quality () inline
Definition at line 37 of file quality.h.
Member Function Documentation
gain()
typeQuality Quality::gain (const typeVertex & node, const typeCommunity & comm) const inline virtual
compute the gain in quality by moving the given node from its current community to the given community comm
Parameters
node
comm
Returns
the gain in quality, which may be positive or negative
Implements QualityInterface.
Definition at line 39 of file quality.h.
References BALMOD, BalMod::gain(), Modularity::gain(), and MODULARITY.
Referenced by Louvain::gain().
quality()
typeQuality Quality::quality () const inline virtual
compute the quality of the current partition scheme
Returns
the quality value
Implements QualityInterface.
Definition at line 47 of file quality.h.
References BALMOD, MODULARITY, BalMod::quality(), and Modularity::quality().
Referenced by DynCommBase::quality(), and Louvain::quality().
type()
QUALITY Quality::type () const inline
Returns
the chosen quality formula
Definition at line 59 of file quality.h.
References q.
Member Data Documentation
bal
BalMod Quality::bal private
Definition at line 26 of file quality.h.
mod
Modularity Quality::mod private
Definition at line 25 of file quality.h.
q
const QUALITY Quality::q private
Definition at line 24 of file quality.h.
Referenced by type().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/quality.h