DynComm: DynCommRcpp Class Reference
DynCommRcpp Class Reference
Public Member Functions
DynCommRcpp ()=delete
DynCommRcpp (Algorithm::ALGORITHM algorithm=Algorithm::ALGORITHM::LOUVAIN, const Criterion::CRITERION &quality=Criterion::CRITERION::MODULARITY, Rcpp::CharacterMatrix algorithmParameters=Rcpp::CharacterMatrix())
bool addRemoveEdgesFile (std::string graphAddRemove)
bool addRemoveEdgesMatrix (Rcpp::NumericMatrix graphAddRemove=Rcpp::NumericMatrix())
double quality ()
int communityCount ()
Rcpp::NumericVector communities ()
Rcpp::NumericMatrix communityNeighbours (typeCommunity community) const
typeWeight communityInnerEdgesWeight (int community)
typeWeight communityTotalWeight (int community)
typeWeight communityEdgeWeight (typeCommunity source, typeCommunity destination) const
int communityVertexCount (int community)
typeCommunity community (typeVertex vertex) const
unsigned int vertexCount () const
Rcpp::NumericVector verticesAll ()
Rcpp::NumericVector vertices (int community)
Rcpp::NumericMatrix communityMappingMatrix (bool differential=true)
Rcpp::NumericMatrix communityMappingFile (bool communityFirst=true, bool differential=true, const std::string &file="communityMapping.txt")
Rcpp::CharacterMatrix results (bool differential=true)
Rcpp::NumericMatrix neighbours (typeVertex vertex) const
typeWeight edgeWeight (typeVertex source, typeVertex destination) const
uint64 time (bool differential=false)
Private Member Functions
ProgramParameters convertToParameters (Rcpp::CharacterMatrix algorithmParameters=Rcpp::CharacterMatrix())
Private Attributes
ProgramParameters prmtrs
DynCommBase dcb
Detailed Description
Dynamic Communities class that handles all the IO for the base class. This (file/class) is the R version.
Definition at line 48 of file DynCommRcpp.cpp.
Constructor & Destructor Documentation
DynCommRcpp() [1/2]
DynCommRcpp::DynCommRcpp () delete
Default constructor not acceptable. Must be passed at least the chosen algorithm and the graph
DynCommRcpp() [2/2]
DynCommRcpp::DynCommRcpp (Algorithm::ALGORITHM algorithm = Algorithm::ALGORITHM::LOUVAIN, const Criterion::CRITERION & quality = Criterion::CRITERION::MODULARITY, Rcpp::CharacterMatrix algorithmParameters = Rcpp::CharacterMatrix()) inline
Constructor for loading graph from white character (tab or space) separated values file Format of file is:
one edge per line
edge contains two or three values separated by a white space, in this order, source vertex, destination vertex and, optionally, a weight
if weight is not given, it will default to 1
edges with a weight of exactly zero are not added
source and destination vertices are integers between 0 and MAX_INTEGER_VALUE-1
weight is a double
MAX_INTEGER_VALUE depends on the platform being 32bit or 64bit. It is the maximum value of an integer in that platform
Definition at line 95 of file DynCommRcpp.cpp.
Member Function Documentation
addRemoveEdgesFile()
bool DynCommRcpp::addRemoveEdgesFile (std::string graphAddRemove) inline
Function to add and remove edges from the graph using a file. After successfully adding/removing, the algorithm will automatically run again. Any edge with a weight different from zero is inserted. Any edge with a weight of exactly zero is removed. The weight column is optional Format of the file is:
one edge per line
edge contains two or three columns, in this order, source vertex, destination vertex and, optionally, a weight
if weight is not given, it will default to 1
edges with a weight of exactly zero are removed
source and destination vertices are integers between 0 and MAX_INTEGER_VALUE-1
weight is a double
MAX_INTEGER_VALUE depends on the platform being 32bit or 64bit. It is the maximum value of an integer in that platform
Returns
true if adding/removing succeeded
Definition at line 122 of file DynCommRcpp.cpp.
References DynCommBase::addRemoveEdges(), and ProgramParameters::filename.
Referenced by RCPP_MODULE().
addRemoveEdgesMatrix()
bool DynCommRcpp::addRemoveEdgesMatrix (Rcpp::NumericMatrix graphAddRemove = Rcpp::NumericMatrix()) inline
Function to add and remove edges from the graph using a matrix. After successfully adding/removing, the algorithm will automatically run again. Any edge with a weight different from zero is inserted. Any edge with a weight of exactly zero is removed. The weight column is optional Format of the matrix is:
one edge per line
edge contains two or three columns, in this order, source vertex, destination vertex and, optionally, a weight
if weight is not given, it will default to 1
edges with a weight of exactly zero are removed
source and destination vertices are integers between 0 and MAX_INTEGER_VALUE-1
weight is a double
MAX_INTEGER_VALUE depends on the platform being 32bit or 64bit. It is the maximum value of an integer in that platform
Returns
true if adding/removing succeeded
Definition at line 146 of file DynCommRcpp.cpp.
References DynCommBase::addRemoveEdges().
Referenced by RCPP_MODULE().
communities()
Rcpp::NumericVector DynCommRcpp::communities () inline
Returns
a list of all communities
Definition at line 170 of file DynCommRcpp.cpp.
References DynCommBase::communities().
Referenced by RCPP_MODULE().
community()
typeCommunity DynCommRcpp::community (typeVertex vertex) const inline
Definition at line 223 of file DynCommRcpp.cpp.
References DynCommBase::community().
Referenced by RCPP_MODULE().
communityCount()
int DynCommRcpp::communityCount () inline
Returns
the number of communities
Definition at line 163 of file DynCommRcpp.cpp.
References DynCommBase::communityCount().
Referenced by RCPP_MODULE().
communityEdgeWeight()
typeWeight DynCommRcpp::communityEdgeWeight (typeCommunity source, typeCommunity destination) const inline
Definition at line 215 of file DynCommRcpp.cpp.
References DynCommBase::communityEdgeWeight().
Referenced by RCPP_MODULE().
communityInnerEdgesWeight()
typeWeight DynCommRcpp::communityInnerEdgesWeight (int community) inline
Definition at line 203 of file DynCommRcpp.cpp.
References DynCommBase::communityInnerEdgesWeight().
Referenced by RCPP_MODULE().
communityMappingFile()
Rcpp::NumericMatrix DynCommRcpp::communityMappingFile (bool communityFirst = true, bool differential = true, const std::string & file = "communityMapping.txt") inline
Get a snapshot of the current community mapping as a R Matrix Format of the file is:
one vertex mapping per line
mapping contains two columns, in this order, vertex and community
vertex and community are integers between 0 and MAX_INTEGER_VALUE-1
MAX_INTEGER_VALUE depends on the platform being 32bit or 64bit. It is the maximum value of an integer in that platform
Definition at line 287 of file DynCommRcpp.cpp.
References DynCommBase::communityMapping(), and ProgramParameters::outfilename.
Referenced by RCPP_MODULE().
communityMappingMatrix()
Rcpp::NumericMatrix DynCommRcpp::communityMappingMatrix (bool differential = true) inline
Get a snapshot of the current community mapping as a R Matrix Format of the file is:
one vertex mapping per line
mapping contains two columns, in this order, vertex and community
vertex and community are integers between 0 and MAX_INTEGER_VALUE-1
MAX_INTEGER_VALUE depends on the platform being 32bit or 64bit. It is the maximum value of an integer in that platform
Definition at line 266 of file DynCommRcpp.cpp.
References DynCommBase::community(), DynCommBase::vertexCount(), and DynCommBase::vertices().
Referenced by RCPP_MODULE().
communityNeighbours()
Rcpp::NumericMatrix DynCommRcpp::communityNeighbours (typeCommunity community) const inline
Returns
a matrix of neighboring communities of the given community and the weight of their edge
Definition at line 185 of file DynCommRcpp.cpp.
References DynCommBase::communityNeighbours().
Referenced by RCPP_MODULE().
communityTotalWeight()
typeWeight DynCommRcpp::communityTotalWeight (int community) inline
Definition at line 209 of file DynCommRcpp.cpp.
References DynCommBase::communityTotalWeight().
Referenced by RCPP_MODULE().
communityVertexCount()
int DynCommRcpp::communityVertexCount (int community) inline
Definition at line 219 of file DynCommRcpp.cpp.
References DynCommBase::communityVertexCount().
Referenced by RCPP_MODULE().
convertToParameters()
ProgramParameters DynCommRcpp::convertToParameters (Rcpp::CharacterMatrix algorithmParameters = Rcpp::CharacterMatrix()) inline private
Definition at line 53 of file DynCommRcpp.cpp.
References parse_arg().
edgeWeight()
typeWeight DynCommRcpp::edgeWeight (typeVertex source, typeVertex destination) const inline
Definition at line 326 of file DynCommRcpp.cpp.
References DynCommBase::weight().
Referenced by RCPP_MODULE().
neighbours()
Rcpp::NumericMatrix DynCommRcpp::neighbours (typeVertex vertex) const inline
Returns
a list of neighboring communities of the given community
Definition at line 308 of file DynCommRcpp.cpp.
References DynCommBase::neighbours().
Referenced by RCPP_MODULE().
quality()
double DynCommRcpp::quality () inline
Returns
the current quality measure of the community mapping on the graph
Definition at line 156 of file DynCommRcpp.cpp.
References DynCommBase::quality().
Referenced by RCPP_MODULE().
results()
Rcpp::CharacterMatrix DynCommRcpp::results (bool differential = true) inline
Definition at line 298 of file DynCommRcpp.cpp.
References DynCommBase::time().
Referenced by RCPP_MODULE().
time()
uint64 DynCommRcpp::time (bool differential = false) inline
Definition at line 330 of file DynCommRcpp.cpp.
References DynCommBase::time().
Referenced by RCPP_MODULE().
vertexCount()
unsigned int DynCommRcpp::vertexCount () const inline
Definition at line 227 of file DynCommRcpp.cpp.
References DynCommBase::vertexCount().
Referenced by RCPP_MODULE().
vertices()
Rcpp::NumericVector DynCommRcpp::vertices (int community) inline
Returns
a list of all vertices belonging to the given community
Definition at line 246 of file DynCommRcpp.cpp.
References DynCommBase::vertices().
Referenced by RCPP_MODULE().
verticesAll()
Rcpp::NumericVector DynCommRcpp::verticesAll () inline
Definition at line 231 of file DynCommRcpp.cpp.
References DynCommBase::vertices().
Referenced by RCPP_MODULE().
Member Data Documentation
dcb
DynCommBase DynCommRcpp::dcb private
Definition at line 51 of file DynCommRcpp.cpp.
prmtrs
ProgramParameters DynCommRcpp::prmtrs private
Definition at line 50 of file DynCommRcpp.cpp.
The documentation for this class was generated from the following file:
R-CRAN/src/DynCommRcpp.cpp