DynComm: QualityInterface Class Reference
QualityInterface Class Reference abstract
#include <qualityInterface.h>
Public Member Functions
virtual ~QualityInterface ()
virtual typeQuality gain (const typeVertex &node, const typeCommunity &comm) const =0
virtual typeQuality quality () const =0
Detailed Description
Definition at line 16 of file qualityInterface.h.
Constructor & Destructor Documentation
~QualityInterface()
virtual QualityInterface::~QualityInterface () inline virtual
Definition at line 18 of file qualityInterface.h.
References gain(), and quality().
Member Function Documentation
gain()
virtual typeQuality QualityInterface::gain (const typeVertex & node, const typeCommunity & comm) const pure virtual
compute the gain in quality by moving the given node from its current community to the given community comm
Parameters
node
comm
Returns
the gain in quality, which may be positive or negative
Implemented in Louvain, Quality, Modularity, and BalMod.
Referenced by ~QualityInterface().
quality()
virtual typeQuality QualityInterface::quality () const pure virtual
compute the quality of the current partition scheme
Returns
the quality value
Implemented in Louvain, Modularity, Quality, and BalMod.
Referenced by ~QualityInterface().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/qualityInterface.h