DynComm: ReaderInterface< TYPERETURN > Class Template Reference
ReaderInterface< TYPERETURN > Class Template Reference abstract
Interface for a simple stream forward reader.
#include <reader.h>
Public Types
enum READTYPE : unsigned int { READTYPE::LINE =1, READTYPE::VALUE, READTYPE::COMMENT }
enum NEXTTYPE : unsigned int {
NEXTTYPE::CANNOTOPEN =1, NEXTTYPE::ENDOFFILE, NEXTTYPE::NEWLINE, NEXTTYPE::VALUE,
NEXTTYPE::COMMENT
}
Public Member Functions
virtual ~ReaderInterface ()
virtual NEXTTYPE hasNext ()=0
virtual TYPERETURN next (READTYPE type=READTYPE::VALUE)=0
virtual std::string status ()=0
Detailed Description
template<typename TYPERETURN>
class ReaderInterface< TYPERETURN >
Interface for a simple stream forward reader.
Format is one set of values per line, with values separated by any white space (space or tab) in any amount. Readers that implement this interface can not read backwards.
Author
poltergeist0
Date
2019-02-06
Definition at line 41 of file reader.h.
Member Enumeration Documentation
NEXTTYPE
template<typename TYPERETURN> enum ReaderInterface::NEXTTYPE : unsigned int strong
Enumeration of the type of object that is next is line for reading
Enumerator
CANNOTOPEN
ENDOFFILE
NEWLINE
VALUE
COMMENT
Definition at line 51 of file reader.h.
READTYPE
template<typename TYPERETURN> enum ReaderInterface::READTYPE : unsigned int strong
Enumeration of the types of objects that can be read
Enumerator
LINE
VALUE
COMMENT
Definition at line 46 of file reader.h.
Constructor & Destructor Documentation
~ReaderInterface()
template<typename TYPERETURN> virtual ReaderInterface< TYPERETURN >::~ReaderInterface () inline virtual
Definition at line 53 of file reader.h.
Member Function Documentation
hasNext()
template<typename TYPERETURN> virtual NEXTTYPE ReaderInterface< TYPERETURN >::hasNext () pure virtual
Returns
the type of the next object that can be read
Implemented in ReaderMatrixEdge, ReaderStringEdge, ReaderFileEdge, and ReaderDummy.
Referenced by Algorithm::addRemoveEdges(), and ReaderInterface< Edge >::~ReaderInterface().
next()
template<typename TYPERETURN> virtual TYPERETURN ReaderInterface< TYPERETURN >::next (READTYPE type = READTYPE::VALUE) pure virtual
Parameters
type
Returns
the next object of the given type ignoring any other type
Implemented in ReaderMatrixEdge, ReaderStringEdge, ReaderFileEdge, and ReaderDummy.
Referenced by Algorithm::addRemoveEdges(), ReaderFileEdge::ReaderFileEdge(), ReaderMatrixEdge::ReaderMatrixEdge(), ReaderStringEdge::ReaderStringEdge(), and ReaderInterface< Edge >::~ReaderInterface().
status()
template<typename TYPERETURN> virtual std::string ReaderInterface< TYPERETURN >::status () pure virtual
Returns
either an ok message or an error message
Implemented in ReaderMatrixEdge, ReaderStringEdge, ReaderFileEdge, and ReaderDummy.
Referenced by ReaderInterface< Edge >::~ReaderInterface().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/reader.h