DynComm: MultimapReversable< T, U > Class Template Reference
MultimapReversable< T, U > Class Template Reference
Doubly indexed multimap.
#include <multimapReversable.h>
Public Types
typedef std::multimap< T, U >::const_iterator const_iterator
typedef std::multimap< U, T >::const_iterator const_range_iterator
Public Member Functions
MultimapReversable ()
MultimapReversable (equalValues e)
const_iterator find (const T &key) const
std::set< T > keys () const
std::pair< const_range_iterator, const_range_iterator > keys (const U &value) const
std::set< T > values () const
const_iterator & cbegin () const
const_iterator cend () const
bool add (const T &key, const U &value, const bool &replace=false)
bool remove (const T &first, const U &second)
void replace (const U &oldValue, const U &newValue)
std::string toString () const
Private Types
typedef std::multimap< T, U >::iterator iterator
typedef std::multimap< U, T >::iterator range_iterator
typedef bool(* equalValues) (const U &, const U &)
Private Attributes
std::multimap< T, U > f
std::multimap< U, T > r
equalValues eq
Detailed Description
template<typename T, typename U>
class MultimapReversable< T, U >
Doubly indexed multimap.
Class that implements a multimap in which the values are also indexed. Unlike an ordinary std::multimap which is indexed by key only, this multimap is also indexed by value.
Author
poltergeist0
Date
2018-08-19
Definition at line 41 of file multimapReversable.h.
Member Typedef Documentation
const_iterator
template<typename T , typename U > typedef std::multimap<T,U>::const_iterator MultimapReversable< T, U >::const_iterator
Definition at line 55 of file multimapReversable.h.
const_range_iterator
template<typename T , typename U > typedef std::multimap<U,T>::const_iterator MultimapReversable< T, U >::const_range_iterator
Definition at line 56 of file multimapReversable.h.
equalValues
template<typename T , typename U > typedef bool(* MultimapReversable< T, U >::equalValues) (const U &, const U &) private
Definition at line 49 of file multimapReversable.h.
iterator
template<typename T , typename U > typedef std::multimap<T,U>::iterator MultimapReversable< T, U >::iterator private
Definition at line 46 of file multimapReversable.h.
range_iterator
template<typename T , typename U > typedef std::multimap<U,T>::iterator MultimapReversable< T, U >::range_iterator private
Definition at line 47 of file multimapReversable.h.
Constructor & Destructor Documentation
MultimapReversable() [1/2]
template<typename T , typename U > MultimapReversable< T, U >::MultimapReversable () inline
default constructor
Definition at line 61 of file multimapReversable.h.
MultimapReversable() [2/2]
template<typename T , typename U > MultimapReversable< T, U >::MultimapReversable (equalValues e) inline
Definition at line 63 of file multimapReversable.h.
Member Function Documentation
add()
template<typename T , typename U > bool MultimapReversable< T, U >::add (const T & key, const U & value, const bool & replace = false) inline
Add a (key, value) pair to the map
Parameters
key
value
replace,if true and key exists, replaces the value otherwise fails. If false and key exists fails.
Returns
true if insertion succeeds
Definition at line 110 of file multimapReversable.h.
References multimap::find(), and MultimapReversable< T, U >::replace().
cbegin()
template<typename T , typename U > const_iterator& MultimapReversable< T, U >::cbegin () const inline
Returns
a constant iterator to the beginning of the map
Definition at line 95 of file multimapReversable.h.
cend()
template<typename T , typename U > const_iterator MultimapReversable< T, U >::cend () const inline
Returns
a constant iterator to the end of the map
Definition at line 100 of file multimapReversable.h.
find()
template<typename T , typename U > const_iterator MultimapReversable< T, U >::find (const T & key) const inline
Find the value attributed to a given key
Parameters
key
Returns
a constant iterator that points to the pair that holds the (key, value) or cend() if not found
Definition at line 70 of file multimapReversable.h.
keys() [1/2]
template<typename T , typename U > std::set<T> MultimapReversable< T, U >::keys () const inline
Compatibility function with multimap since in a map all keys are unique
Returns
all unique keys in the map
Definition at line 76 of file multimapReversable.h.
References MultimapReversable< T, U >::keys().
Referenced by MultimapReversable< T, U >::keys().
keys() [2/2]
template<typename T , typename U > std::pair<const_range_iterator,const_range_iterator> MultimapReversable< T, U >::keys (const U & value) const inline
get all the keys that have a given value
Parameters
value
Returns
a pair of constant range iterators pointing, respectively, to the beginning and to the end of the range of keys that holds the given value
Definition at line 83 of file multimapReversable.h.
remove()
template<typename T , typename U > bool MultimapReversable< T, U >::remove (const T & first, const U & second) inline
remove a (key,value) pair
Parameters
first
second
Returns
true if the element existed otherwise false
Definition at line 140 of file multimapReversable.h.
References multimap::find().
replace()
template<typename T , typename U > void MultimapReversable< T, U >::replace (const U & oldValue, const U & newValue) inline
Replace all occurrences of oldValue by newValue
Parameters
oldValue
newValue
Definition at line 158 of file multimapReversable.h.
Referenced by MultimapReversable< T, U >::add().
toString()
template<typename T , typename U > std::string MultimapReversable< T, U >::toString () const inline
Returns
a string representation of this map list and reverse list
Definition at line 175 of file multimapReversable.h.
References multimap::toString().
values()
template<typename T , typename U > std::set<T> MultimapReversable< T, U >::values () const inline
Returns
all unique values in the map
Definition at line 89 of file multimapReversable.h.
References MultimapReversable< T, U >::values().
Referenced by MultimapReversable< T, U >::values().
Member Data Documentation
eq
template<typename T , typename U > equalValues MultimapReversable< T, U >::eq private
Definition at line 51 of file multimapReversable.h.
f
template<typename T , typename U > std::multimap<T,U> MultimapReversable< T, U >::f private
Definition at line 43 of file multimapReversable.h.
r
template<typename T , typename U > std::multimap<U,T> MultimapReversable< T, U >::r private
Definition at line 44 of file multimapReversable.h.
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/multimapReversable.h