DynComm: BalMod Class Reference
BalMod Class Reference
#include <qualityBalMod.h>
Public Member Functions
BalMod (GraphUndirectedGroupable &graph, const ProgramParameters &parameters=argumentsDefault)
~BalMod ()
typeQuality gain (const typeVertex &node, const typeCommunity &comm) const
typeQuality quality () const
Public Member Functions inherited from QualityBase
QualityBase (const GraphUndirectedGroupable &graph, const ProgramParameters &parameters=argumentsDefault)
virtual ~QualityBase ()
Public Member Functions inherited from QualityInterface
virtual ~QualityInterface ()
Additional Inherited Members
Protected Attributes inherited from QualityBase
const GraphUndirectedGroupable & g
const ProgramParameters & prmtrs
Detailed Description
Definition at line 13 of file qualityBalMod.h.
Constructor & Destructor Documentation
BalMod()
BalMod::BalMod (GraphUndirectedGroupable & graph, const ProgramParameters & parameters = argumentsDefault) inline
Definition at line 16 of file qualityBalMod.h.
~BalMod()
BalMod::~BalMod () inline
Definition at line 18 of file qualityBalMod.h.
Member Function Documentation
gain()
typeQuality BalMod::gain (const typeVertex & node, const typeCommunity & comm) const inline virtual
compute the gain in quality by moving the given node from its current community to the given community comm
Parameters
node
comm
Returns
the gain in quality, which may be positive or negative
Implements QualityInterface.
Definition at line 20 of file qualityBalMod.h.
References GraphUndirectedGroupable::community(), QualityBase::g, GraphUndirectedGroupable::neighborsCommunityWeight(), GraphUndirectedGroupable::totalEdges(), GraphUndirected::totalWeight(), and GraphUndirected::weighted_degree().
Referenced by Quality::gain().
quality()
typeQuality BalMod::quality () const inline virtual
compute the quality of the current partition scheme
Returns
the quality value
Implements QualityInterface.
Definition at line 41 of file qualityBalMod.h.
References QualityBase::g, GraphUndirected::getVertices(), GraphUndirectedGroupable::innerEdges(), GraphUndirectedGroupable::totalEdges(), and GraphUndirected::totalWeight().
Referenced by Quality::quality().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/qualityBalMod.h