DynComm: CriterionBalMod Class Reference
CriterionBalMod Class Reference
Balanced Modularity criterion.
#include <criterionBalMod.h>
Public Member Functions
CriterionBalMod (const GraphUndirectedGroupable &graph, const ProgramParameters &parameters=argumentsDefault)
~CriterionBalMod ()
typeCriterion gain (const typeVertex &vertex, const typeCommunity &comm) const
typeCriterion quality () const
Public Member Functions inherited from CriterionBase
CriterionBase (const GraphUndirectedGroupable &graph, const ProgramParameters &parameters=argumentsDefault)
virtual ~CriterionBase ()
Public Member Functions inherited from CriterionInterface
virtual ~CriterionInterface ()
Additional Inherited Members
Protected Attributes inherited from CriterionBase
const GraphUndirectedGroupable & g
const ProgramParameters & prmtrs
Detailed Description
Balanced Modularity criterion.
Author
poltergeist0
Date
2018-08-20
Definition at line 29 of file criterionBalMod.h.
Constructor & Destructor Documentation
CriterionBalMod()
CriterionBalMod::CriterionBalMod (const GraphUndirectedGroupable & graph, const ProgramParameters & parameters = argumentsDefault) inline
Constructor.
Parameters
graph reference to the graph object
parameters reference to the parameters object
Definition at line 39 of file criterionBalMod.h.
~CriterionBalMod()
CriterionBalMod::~CriterionBalMod () inline
Destructor
Definition at line 44 of file criterionBalMod.h.
Member Function Documentation
gain()
typeCriterion CriterionBalMod::gain (const typeVertex & vertex, const typeCommunity & comm) const inline virtual
compute the quality obtained if the given vertex was moved from its current community to the given community
Parameters
vertex
comm new potential community for given vertex
Returns
the quality, which may be positive or negative
Implements CriterionInterface.
Definition at line 54 of file criterionBalMod.h.
References GraphUndirectedGroupable::community(), CriterionBase::g, GraphUndirectedGroupable::neighboursCommunityWeight(), GraphUndirectedGroupable::totalEdges(), GraphUndirected::totalWeight(), and GraphUndirected::weighted_degree().
Referenced by Criterion::gain().
quality()
typeCriterion CriterionBalMod::quality () const inline virtual
compute the quality of the current partition scheme
Returns
the quality value
Implements CriterionInterface.
Definition at line 70 of file criterionBalMod.h.
References CriterionBase::g, GraphUndirected::getVertices(), GraphUndirectedGroupable::innerEdges(), GraphUndirectedGroupable::totalEdges(), and GraphUndirected::totalWeight().
Referenced by Criterion::quality().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/criterionBalMod.h