DynComm: AlgorithmLouvain Class Reference
AlgorithmLouvain Class Reference
Class that implements the Dynamic Louvain algorithm.
#include <algorithmLouvain.h>
Public Member Functions
bool addRemoveEdgePre (const typeVertex &source, const typeVertex &destination, const typeWeight &weight=1.0)
bool addRemoveEdgePost (const typeVertex &source, const typeVertex &destination, const typeWeight &weight=1.0)
bool run ()
AlgorithmLouvain ()=delete
~AlgorithmLouvain ()
AlgorithmLouvain (GraphUndirectedGroupable &graph, const Criterion &quality, const ProgramParameters &algorithmParameters=argumentsDefault)
const std::string toString (const StringFormatter &sf=defaultStringFormatter) const
Private Member Functions
const typeCommunity & community (const typeVertex &node) const
bool community (const typeVertex &node, const typeCommunity &com)
typeWeight innerEdges (const typeCommunity &c) const
typeWeight totalEdges (const typeCommunity &c) const
typeLinksRangeConst edges () const
const typeVertexList & getVertices () const
typeCommunityListRange vertices (const typeCommunity &c)
typeLinksRangeConst neighbours (const typeVertex &node) const
unsigned int neighboursCount (const typeVertex &node) const
unsigned int neighboursCommunityCount (const typeVertex &node) const
typeWeight neighboursCommunityWeight (const typeVertex &node, const typeCommunity &com)
typeWeight neighboursCommunityWeight (const typeVertex &node)
const typeWeight & maxWeight () const
const typeWeight totalWeight () const
const typeWeight verticesCount () const
const typeWeight edgeCount () const
const typeWeight communityCount () const
typeWeight weighted_degree (const typeVertex &vertex) const
typeCriterion gain (const typeVertex &vertex, const typeCommunity &comm) const
typeCriterion quality () const
void disband (const typeCommunity c1, const typeCommunity c2)
std::map< typeCommunity, typeWeight > neigh_comm (const typeVertex &vertex) const
bool one_level ()
Private Member Functions inherited from AlgorithmBase
AlgorithmBase ()=delete
virtual ~AlgorithmBase ()
AlgorithmBase (GraphUndirectedGroupable &graph, const Criterion &quality, const ProgramParameters &parameters=argumentsDefault)
const std::string toString (const StringFormatter &sf=defaultStringFormatter) const
Private Member Functions inherited from AlgorithmInterface
virtual ~AlgorithmInterface ()
Private Attributes
GraphUndirectedGroupable cg
Criterion qltc
bool firstRun =true
Private Attributes inherited from AlgorithmBase
GraphUndirectedGroupable & grph
const ProgramParameters & prmtrs
const Criterion & qlt
Detailed Description
Class that implements the Dynamic Louvain algorithm.
The Dynamic Louvain algorithm is a greedy optimization method to extract communities from large networks by optimizing the density of edges inside communities to edges outside communities.
Author
poltergeist0
Date
2019-01-01
Definition at line 34 of file algorithmLouvain.h.
Constructor & Destructor Documentation
AlgorithmLouvain() [1/2]
AlgorithmLouvain::AlgorithmLouvain () delete
Default constructor not acceptable. Must be passed at least the chosen algorithm and the graph
Referenced by run().
~AlgorithmLouvain()
AlgorithmLouvain::~AlgorithmLouvain () inline
Destructor
Definition at line 497 of file algorithmLouvain.h.
AlgorithmLouvain() [2/2]
AlgorithmLouvain::AlgorithmLouvain (GraphUndirectedGroupable & graph, const Criterion & quality, const ProgramParameters & algorithmParameters = argumentsDefault) inline
Constructor.
Parameters
graph reference to the graph object
quality reference to the quality object
algorithmParameters reference to the parameters object
Definition at line 506 of file algorithmLouvain.h.
Member Function Documentation
addRemoveEdgePost()
bool AlgorithmLouvain::addRemoveEdgePost (const typeVertex & source, const typeVertex & destination, const typeWeight & weight = 1.0) inline virtual
Function execute after adding or removing a single edge from the graph. It is used internally by the addRemoveEdges function. Useful if post-processing is required, for example, to update some of variables after the edge has be added or removed. Any edge with a weight different from zero is inserted. Any edge with a weight of exactly zero is removed.
Parameters
source source vertex
destination destination vertex
weight optional if adding an edge. Must be exactly zero to remove an edge.
Returns
true if all operations succeeded. False, otherwise.
Implements AlgorithmInterface.
Definition at line 438 of file algorithmLouvain.h.
References GraphUndirectedGroupable::addEdge(), GraphUndirectedGroupable::community(), disband(), AlgorithmBase::grph, and GraphUndirected::weight().
Referenced by Algorithm::addRemoveEdgePost().
addRemoveEdgePre()
bool AlgorithmLouvain::addRemoveEdgePre (const typeVertex & source, const typeVertex & destination, const typeWeight & weight = 1.0) inline virtual
Function to execute before adding or removing a single edge from the graph. It is used internally by the addRemoveEdges function. Useful if pre-processing is required, for example, to update some of variables before the edge can be added or removed. Any edge with a weight different from zero is inserted. Any edge with a weight of exactly zero is removed.
Parameters
source source vertex
destination destination vertex
weight optional if adding an edge. Must be exactly zero to remove an edge.
Returns
true if all operations succeeded. False, otherwise.
Implements AlgorithmInterface.
Definition at line 401 of file algorithmLouvain.h.
References GraphUndirectedGroupable::addEdge(), GraphUndirectedGroupable::community(), AlgorithmBase::grph, GraphUndirectedGroupable::removeEdge(), and GraphUndirected::weight().
Referenced by Algorithm::addRemoveEdgePre().
community() [1/2]
const typeCommunity& AlgorithmLouvain::community (const typeVertex & node) const inline private
Definition at line 65 of file algorithmLouvain.h.
References GraphUndirectedGroupable::community(), AlgorithmBase::grph, and noGroup.
Referenced by neigh_comm(), and one_level().
community() [2/2]
bool AlgorithmLouvain::community (const typeVertex & node, const typeCommunity & com) inline private
Definition at line 73 of file algorithmLouvain.h.
References GraphUndirectedGroupable::community(), and AlgorithmBase::grph.
communityCount()
const typeWeight AlgorithmLouvain::communityCount () const inline private
Definition at line 152 of file algorithmLouvain.h.
References GraphUndirectedGroupable::communityCount(), and AlgorithmBase::grph.
disband()
void AlgorithmLouvain::disband (const typeCommunity c1, const typeCommunity c2) inline private
Disband communities belonging to the given edge. Source and destination communities must be different. It is an algorithm requirement that, when adding edges, the communities involved get removed and replaced by their individual vertices, so that calculation are only performed over those vertices, making the Louvain algorithm dynamic.
Parameters
c1 the source community of the edge
c2 the destination community of the edge
Definition at line 195 of file algorithmLouvain.h.
References GraphUndirectedGroupable::addEdge(), GraphUndirectedGroupable::community(), HalfEdge::destination(), GraphUndirectedGroupable::disband(), AlgorithmBase::grph, GraphUndirectedGroupable::neighbouringCommunities(), GraphUndirected::neighbours(), GraphUndirectedGroupable::removeEdge(), GraphUndirectedGroupable::vertices(), and HalfEdge::weight().
Referenced by addRemoveEdgePost().
edgeCount()
const typeWeight AlgorithmLouvain::edgeCount () const inline private
Definition at line 147 of file algorithmLouvain.h.
References GraphUndirected::edgeCount(), and AlgorithmBase::grph.
edges()
typeLinksRangeConst AlgorithmLouvain::edges () const inline private
Definition at line 92 of file algorithmLouvain.h.
References GraphUndirected::edges(), and AlgorithmBase::grph.
gain()
typeCriterion AlgorithmLouvain::gain (const typeVertex & vertex, const typeCommunity & comm) const inline private
Definition at line 169 of file algorithmLouvain.h.
References Criterion::gain(), and AlgorithmBase::qlt.
Referenced by one_level().
getVertices()
const typeVertexList& AlgorithmLouvain::getVertices () const inline private
Definition at line 97 of file algorithmLouvain.h.
References GraphUndirected::getVertices(), and AlgorithmBase::grph.
Referenced by one_level().
innerEdges()
typeWeight AlgorithmLouvain::innerEdges (const typeCommunity & c) const inline private
Definition at line 82 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::innerEdges().
maxWeight()
const typeWeight& AlgorithmLouvain::maxWeight () const inline private
Definition at line 132 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::maxWeight().
neigh_comm()
std::map<typeCommunity, typeWeight> AlgorithmLouvain::neigh_comm (const typeVertex & vertex) const inline private
Get the neighbouring communities of the given vertex with edge weight
Parameters
vertex
Returns
the neighbouring communities of the given vertex
Definition at line 266 of file algorithmLouvain.h.
References community(), HalfEdge::destination(), neighbours(), noVertex, and HalfEdge::weight().
Referenced by one_level().
neighbours()
typeLinksRangeConst AlgorithmLouvain::neighbours (const typeVertex & node) const inline private
Definition at line 107 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::neighbours().
Referenced by neigh_comm(), and one_level().
neighboursCommunityCount()
unsigned int AlgorithmLouvain::neighboursCommunityCount (const typeVertex & node) const inline private
Definition at line 117 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::neighboursCommunityCount().
neighboursCommunityWeight() [1/2]
typeWeight AlgorithmLouvain::neighboursCommunityWeight (const typeVertex & node, const typeCommunity & com) inline private
Definition at line 122 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::neighboursCommunityWeight().
neighboursCommunityWeight() [2/2]
typeWeight AlgorithmLouvain::neighboursCommunityWeight (const typeVertex & node) inline private
Definition at line 127 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::neighboursCommunityWeight().
neighboursCount()
unsigned int AlgorithmLouvain::neighboursCount (const typeVertex & node) const inline private
Definition at line 112 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::neighboursCount().
one_level()
bool AlgorithmLouvain::one_level () inline private
Function where the actual algorithm is implemented
Returns
true if there was an improvement in quality. False, otherwise
Definition at line 294 of file algorithmLouvain.h.
References GraphUndirectedGroupable::addEdge(), GraphUndirectedGroupable::communities(), GraphUndirectedGroupable::communitiesToGraph(), community(), GraphUndirectedGroupable::community(), HalfEdge::destination(), gain(), getVertices(), GraphUndirected::getVertices(), AlgorithmBase::grph, GraphUndirectedGroupable::innerEdges(), neigh_comm(), GraphUndirectedGroupable::neighbouringCommunities(), neighbours(), ProgramParameters::precision, AlgorithmBase::prmtrs, quality(), GraphUndirectedGroupable::vertices(), and HalfEdge::weight().
Referenced by run().
quality()
typeCriterion AlgorithmLouvain::quality () const inline private
Definition at line 174 of file algorithmLouvain.h.
References AlgorithmBase::qlt, and Criterion::quality().
Referenced by one_level().
run()
bool AlgorithmLouvain::run () inline virtual
Function where the actual algorithms are implemented. It is called at the end of the addRemoveEdges function.
Returns
true if all operations succeeded. False, otherwise.
Implements AlgorithmInterface.
Definition at line 474 of file algorithmLouvain.h.
References AlgorithmLouvain(), and one_level().
Referenced by Algorithm::run().
toString()
const std::string AlgorithmLouvain::toString (const StringFormatter & sf = defaultStringFormatter) const inline
Function that converts this object to a string representation. Might be useful for debugging.
Parameters
sf is a StringFormater object that facilitates formating
Returns
the string representing this object
Definition at line 523 of file algorithmLouvain.h.
References StringFormatter::build(), StringFormatter::header(), AlgorithmBase::toString(), and GraphUndirectedGroupable::toString().
Referenced by Algorithm::toString().
totalEdges()
typeWeight AlgorithmLouvain::totalEdges (const typeCommunity & c) const inline private
Definition at line 87 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::totalEdges().
totalWeight()
const typeWeight AlgorithmLouvain::totalWeight () const inline private
Definition at line 137 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::totalWeight().
vertices()
typeCommunityListRange AlgorithmLouvain::vertices (const typeCommunity & c) inline private
Definition at line 102 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirectedGroupable::vertices().
verticesCount()
const typeWeight AlgorithmLouvain::verticesCount () const inline private
Definition at line 142 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::vertexCount().
weighted_degree()
typeWeight AlgorithmLouvain::weighted_degree (const typeVertex & vertex) const inline private
Definition at line 157 of file algorithmLouvain.h.
References AlgorithmBase::grph, and GraphUndirected::weighted_degree().
Member Data Documentation
cg
GraphUndirectedGroupable AlgorithmLouvain::cg private
Definition at line 40 of file algorithmLouvain.h.
firstRun
bool AlgorithmLouvain::firstRun =true private
Definition at line 56 of file algorithmLouvain.h.
qltc
Criterion AlgorithmLouvain::qltc private
Definition at line 48 of file algorithmLouvain.h.
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/algorithmLouvain.h