DynComm: HalfEdge Class Reference
HalfEdge Class Reference
Half edge class.
#include <edge.h>
Public Member Functions
const typeVertex & destination () const
const bool destination (const typeVertex &destination)
const typeWeight & weight () const
const bool weight (const typeWeight &weight)
HalfEdge (const typeVertex &destination, const typeWeight &weight=0)
const bool operator< (const HalfEdge &rhs) const
const bool operator== (const HalfEdge &rhs) const
const bool operator== (const typeVertex &rhs) const
operator const typeVertex & () const
std::string toString (const StringFormatter &sf=defaultStringFormatter) const
Private Attributes
typeVertex dst
typeWeight wght
Detailed Description
Half edge class.
Class that encapsulates the destination vertex and weight portion of an edge as being a half edge.
Author
poltergeist0
Date
2018-08-19
Definition at line 43 of file edge.h.
Constructor & Destructor Documentation
HalfEdge()
HalfEdge::HalfEdge (const typeVertex & destination, const typeWeight & weight = 0) inline
Constructor with a weight of zero as default
Parameters
destination
weight
Definition at line 86 of file edge.h.
Member Function Documentation
destination() [1/2]
const typeVertex& HalfEdge::destination () const inline
Returns
the destination
Definition at line 53 of file edge.h.
References dst.
Referenced by GraphUndirectedGroupable::community(), destination(), Edge::destination(), AlgorithmLouvain::disband(), AlgorithmLouvain::neigh_comm(), GraphUndirectedGroupable::neighborsCommunityCount(), GraphUndirectedGroupable::neighborsCommunityWeight(), AlgorithmLouvain::one_level(), and GraphUndirected::toString().
destination() [2/2]
const bool HalfEdge::destination (const typeVertex & destination) inline
Modify the destination
Parameters
destination
Returns
true if the value was modified successfully
Definition at line 60 of file edge.h.
References destination().
operator const typeVertex &()
HalfEdge::operator const typeVertex & () const inline
Assignment operator to vertex only. Weight is ignored. Assigns the destination portion to a vertex.
Returns
the destination vertex of this half edge
Definition at line 119 of file edge.h.
References dst.
operator<()
const bool HalfEdge::operator< (const HalfEdge & rhs) const inline
Weak comparator for ordering. Weight is ignored
Parameters
rhs is another half edge to compare to
Returns
true if this half edge (destination) is smaller than the given (rhs) half edge (destination)
Definition at line 93 of file edge.h.
References dst.
Referenced by Edge::operator<().
operator==() [1/2]
const bool HalfEdge::operator== (const HalfEdge & rhs) const inline
Comparison operator. Weight is ignored
Parameters
rhs
Returns
true if this half edge (destination) is equal to the given (rhs) half edge (destination)
Definition at line 100 of file edge.h.
References dst.
Referenced by Edge::operator==().
operator==() [2/2]
const bool HalfEdge::operator== (const typeVertex & rhs) const inline
Comparison operator against vertex only. Weight is ignored
Parameters
rhs is the vertex used to compare to
Returns
true if the destination vertex of this half edge is equal to the given vertex
Definition at line 110 of file edge.h.
toString()
std::string HalfEdge::toString (const StringFormatter & sf = defaultStringFormatter) const inline
Returns
a string representation of this half edge
Definition at line 125 of file edge.h.
Referenced by Edge::toString().
weight() [1/2]
const typeWeight& HalfEdge::weight () const inline
Returns
the weight of the edge
Definition at line 69 of file edge.h.
References wght.
Referenced by GraphUndirected::addEdge(), GraphUndirectedGroupable::community(), AlgorithmLouvain::disband(), AlgorithmLouvain::neigh_comm(), GraphUndirectedGroupable::neighborsCommunityWeight(), AlgorithmLouvain::one_level(), GraphUndirected::toString(), GraphUndirected::updateMaxWeight(), GraphUndirected::updateWeight(), weight(), Edge::weight(), GraphUndirected::weight(), and GraphUndirected::weighted_degree().
weight() [2/2]
const bool HalfEdge::weight (const typeWeight & weight) inline
Modify the weight of the edge
Parameters
weight
Returns
true if the value was modified successfully
Definition at line 76 of file edge.h.
References weight().
Member Data Documentation
dst
typeVertex HalfEdge::dst private
Definition at line 45 of file edge.h.
Referenced by destination(), operator const typeVertex &(), operator<(), and operator==().
wght
typeWeight HalfEdge::wght private
Definition at line 46 of file edge.h.
Referenced by weight().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/edge.h