DynComm: CriterionModularity Class Reference
CriterionModularity Class Reference
Newman-Girvan criterion.
#include <criterionModularity.h>
Public Member Functions
CriterionModularity (const GraphUndirectedGroupable &graph, const ProgramParameters &parameters=argumentsDefault)
~CriterionModularity ()
typeCriterion gain (const typeVertex &vertex, const typeCommunity &comm) const
typeCriterion quality () const
Public Member Functions inherited from CriterionBase
CriterionBase (const GraphUndirectedGroupable &graph, const ProgramParameters &parameters=argumentsDefault)
virtual ~CriterionBase ()
Public Member Functions inherited from CriterionInterface
virtual ~CriterionInterface ()
Additional Inherited Members
Protected Attributes inherited from CriterionBase
const GraphUndirectedGroupable & g
const ProgramParameters & prmtrs
Detailed Description
Newman-Girvan criterion.
Author
poltergeist0
Date
2018-08-20
Definition at line 31 of file criterionModularity.h.
Constructor & Destructor Documentation
CriterionModularity()
CriterionModularity::CriterionModularity (const GraphUndirectedGroupable & graph, const ProgramParameters & parameters = argumentsDefault) inline
Constructor.
Parameters
graph reference to the graph object
parameters reference to the parameters object
Definition at line 41 of file criterionModularity.h.
~CriterionModularity()
CriterionModularity::~CriterionModularity () inline
Destructor
Definition at line 46 of file criterionModularity.h.
Member Function Documentation
gain()
typeCriterion CriterionModularity::gain (const typeVertex & vertex, const typeCommunity & comm) const inline virtual
compute the quality obtained if the given vertex was moved from its current community to the given community
Parameters
vertex
comm new potential community for given vertex
Returns
the quality, which may be positive or negative
Implements CriterionInterface.
Definition at line 57 of file criterionModularity.h.
References GraphUndirectedGroupable::community(), CriterionBase::g, GraphUndirectedGroupable::neighboursCommunityWeight(), GraphUndirectedGroupable::totalEdges(), GraphUndirected::totalWeight(), and GraphUndirected::weighted_degree().
Referenced by Criterion::gain().
quality()
typeCriterion CriterionModularity::quality () const inline virtual
compute the quality of the current partition scheme
Returns
the quality value
Implements CriterionInterface.
Definition at line 74 of file criterionModularity.h.
References CriterionBase::g, GraphUndirected::getVertices(), GraphUndirectedGroupable::innerEdges(), GraphUndirectedGroupable::totalEdges(), and GraphUndirected::totalWeight().
Referenced by Criterion::quality().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/criterionModularity.h