DynComm: WriterFile Class Reference
WriterFile Class Reference
Writer to file output stream.
#include <writer.h>
Public Member Functions
WriterFile (const ProgramParameters &parameters)
~WriterFile ()
bool isReady ()
bool write (const std::string &object, const WRITETYPE &type=WRITETYPE::VALUE)
Write a certain type of object to file stream.
std::string status ()
Public Member Functions inherited from WriterInterface
virtual ~WriterInterface ()
Private Attributes
std::ofstream foutput
WriterStream f
Additional Inherited Members
Public Types inherited from WriterInterface
enum WRITETYPE : unsigned int { WRITETYPE::LINE =1, WRITETYPE::VALUE, WRITETYPE::COMMENT }
Detailed Description
Writer to file output stream.
This writer can not write backwards, only append to the end.
Author
poltergeist0
Date
2019-02-06
Definition at line 157 of file writer.h.
Constructor & Destructor Documentation
WriterFile()
WriterFile::WriterFile (const ProgramParameters & parameters) inline
Definition at line 163 of file writer.h.
References ProgramParameters::outfilename.
~WriterFile()
WriterFile::~WriterFile () inline
Definition at line 167 of file writer.h.
Member Function Documentation
isReady()
bool WriterFile::isReady () inline virtual
Returns
true if the sink is ready to be written
Implements WriterInterface.
Definition at line 173 of file writer.h.
References WriterStream::isReady().
status()
std::string WriterFile::status () inline virtual
Returns
either an ok message or an error message
Implements WriterInterface.
Definition at line 197 of file writer.h.
References WriterStream::status().
write()
bool WriterFile::write (const std::string & object, const WRITETYPE & type = WRITETYPE::VALUE) inline virtual
Write a certain type of object to file stream.
The type parameter defines the type of object being written. This is used to automatically add carriage returns, value separators and prepare writing of the next object type.
Parameters
type defines what is being written
Returns
true if writing succeeded
Implements WriterInterface.
Definition at line 190 of file writer.h.
References WriterStream::write().
Member Data Documentation
f
WriterStream WriterFile::f private
Definition at line 160 of file writer.h.
foutput
std::ofstream WriterFile::foutput private
Definition at line 159 of file writer.h.
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/writer.h