DynComm: StringFormater Class Reference
StringFormater Class Reference
#include <stringFormater.h>
Public Member Functions
StringFormater ()
StringFormater (const StringFormater &copy, const bool &autoIndent=true)
StringFormater (const StringFormater &copy, const int indent)
StringFormater operator() (const int indent) const
const std::string & header () const
void header (const std::string &header)
const std::string & setClose () const
void setClose (const std::string &setClose)
const std::string & setOpen () const
void setOpen (const std::string &setOpen)
const std::string & tail () const
void tail (const std::string &tail)
const std::string & tupleClose () const
void tupleClose (const std::string &tupleClose)
const std::string & tupleOpen () const
void tupleOpen (const std::string &tupleOpen)
const std::string & tupleSeparator () const
void tupleSeparator (const std::string &tupleSeparator)
const std::string & valueSeparator () const
void valueSeparator (const std::string &valueSeparator)
std::string indent () const
std::stringstream & start (std::stringstream &ss, const bool &set=false) const
std::string start (const bool &set=false) const
std::stringstream & end (std::stringstream &ss, const bool &set=false) const
std::string end (const bool &set=false) const
std::stringstream & build (std::stringstream &ss, const std::string &message)
std::string build (const std::string &message)
StringFormater & operator++ ()
StringFormater & operator-- ()
bool isDefault () const
Private Attributes
unsigned int indentLevel =0
std::string hdr =""
std::string tl =""
bool lnBrk =true
std::string tplOpn ="("
std::string tplCls =")"
std::string vlSprtr =";"
std::string tplSprtr =""
std::string stOpn ="{"
std::string stCls ="}"
Detailed Description
Definition at line 14 of file stringFormater.h.
Constructor & Destructor Documentation
StringFormater() [1/3]
StringFormater::StringFormater () inline
Definition at line 30 of file stringFormater.h.
Referenced by operator()().
StringFormater() [2/3]
StringFormater::StringFormater (const StringFormater & copy, const bool & autoIndent = true) inline
Definition at line 36 of file stringFormater.h.
References isDefault().
StringFormater() [3/3]
StringFormater::StringFormater (const StringFormater & copy, const int indent) inline
Definition at line 45 of file stringFormater.h.
References indent().
Member Function Documentation
build() [1/2]
std::stringstream& StringFormater::build (std::stringstream & ss, const std::string & message) inline
Definition at line 127 of file stringFormater.h.
References end(), and start().
Referenced by build(), AlgorithmBase::toString(), MapReversable< typeVertex, typeCommunity >::toString(), Louvain::toString(), and GraphUndirectedGroupable::toString().
build() [2/2]
std::string StringFormater::build (const std::string & message) inline
build a string with the given message and the currently configured formating elements
Parameters
message
Returns
Definition at line 138 of file stringFormater.h.
References build().
end() [1/2]
std::stringstream& StringFormater::end (std::stringstream & ss, const bool & set = false) const inline
Definition at line 112 of file stringFormater.h.
References stCls, and tl.
Referenced by build(), end(), and GraphUndirected::toString().
end() [2/2]
std::string StringFormater::end (const bool & set = false) const inline
Definition at line 122 of file stringFormater.h.
References end().
header() [1/2]
const std::string& StringFormater::header () const inline
Definition at line 59 of file stringFormater.h.
References hdr.
Referenced by AlgorithmBase::toString(), MapReversable< typeVertex, typeCommunity >::toString(), GraphUndirected::toString(), Louvain::toString(), and GraphUndirectedGroupable::toString().
header() [2/2]
void StringFormater::header (const std::string & header) inline
Definition at line 61 of file stringFormater.h.
References header().
Referenced by header().
indent()
std::string StringFormater::indent () const inline
Definition at line 91 of file stringFormater.h.
Referenced by start(), and StringFormater().
isDefault()
bool StringFormater::isDefault () const
Definition at line 159 of file stringFormater.h.
References defaultStringFormater.
Referenced by operator--(), and StringFormater().
operator()()
StringFormater StringFormater::operator() (const int indent) const inline
Definition at line 55 of file stringFormater.h.
References StringFormater().
operator++()
StringFormater& StringFormater::operator++ () inline
Definition at line 145 of file stringFormater.h.
operator--()
StringFormater& StringFormater::operator-- () inline
Definition at line 150 of file stringFormater.h.
References defaultStringFormater, and isDefault().
setClose() [1/2]
const std::string& StringFormater::setClose () const inline
Definition at line 63 of file stringFormater.h.
References stCls.
Referenced by GraphUndirected::toString().
setClose() [2/2]
void StringFormater::setClose (const std::string & setClose) inline
Definition at line 65 of file stringFormater.h.
References setClose().
Referenced by setClose().
setOpen() [1/2]
const std::string& StringFormater::setOpen () const inline
Definition at line 67 of file stringFormater.h.
References stOpn.
Referenced by GraphUndirected::toString().
setOpen() [2/2]
void StringFormater::setOpen (const std::string & setOpen) inline
Definition at line 69 of file stringFormater.h.
References setOpen().
Referenced by setOpen().
start() [1/2]
std::stringstream& StringFormater::start (std::stringstream & ss, const bool & set = false) const inline
Definition at line 95 of file stringFormater.h.
References hdr, indent(), and stOpn.
Referenced by build(), start(), and GraphUndirected::toString().
start() [2/2]
std::string StringFormater::start (const bool & set = false) const inline
Definition at line 107 of file stringFormater.h.
References start().
tail() [1/2]
const std::string& StringFormater::tail () const inline
Definition at line 71 of file stringFormater.h.
References tl.
tail() [2/2]
void StringFormater::tail (const std::string & tail) inline
Definition at line 73 of file stringFormater.h.
References tail().
Referenced by tail().
tupleClose() [1/2]
const std::string& StringFormater::tupleClose () const inline
Definition at line 75 of file stringFormater.h.
References tplCls.
Referenced by GraphUndirected::toString().
tupleClose() [2/2]
void StringFormater::tupleClose (const std::string & tupleClose) inline
Definition at line 77 of file stringFormater.h.
References tupleClose().
Referenced by tupleClose().
tupleOpen() [1/2]
const std::string& StringFormater::tupleOpen () const inline
Definition at line 79 of file stringFormater.h.
References tplOpn.
Referenced by GraphUndirected::toString().
tupleOpen() [2/2]
void StringFormater::tupleOpen (const std::string & tupleOpen) inline
Definition at line 81 of file stringFormater.h.
References tupleOpen().
Referenced by tupleOpen().
tupleSeparator() [1/2]
const std::string& StringFormater::tupleSeparator () const inline
Definition at line 83 of file stringFormater.h.
References tplSprtr.
tupleSeparator() [2/2]
void StringFormater::tupleSeparator (const std::string & tupleSeparator) inline
Definition at line 85 of file stringFormater.h.
References tupleSeparator().
Referenced by tupleSeparator().
valueSeparator() [1/2]
const std::string& StringFormater::valueSeparator () const inline
Definition at line 87 of file stringFormater.h.
References vlSprtr.
Referenced by GraphUndirected::toString().
valueSeparator() [2/2]
void StringFormater::valueSeparator (const std::string & valueSeparator) inline
Definition at line 89 of file stringFormater.h.
References valueSeparator().
Referenced by valueSeparator().
Member Data Documentation
hdr
std::string StringFormater::hdr ="" private
Definition at line 17 of file stringFormater.h.
Referenced by header(), and start().
indentLevel
unsigned int StringFormater::indentLevel =0 private
Definition at line 16 of file stringFormater.h.
lnBrk
bool StringFormater::lnBrk =true private
Definition at line 19 of file stringFormater.h.
stCls
std::string StringFormater::stCls ="}" private
Definition at line 25 of file stringFormater.h.
Referenced by end(), and setClose().
stOpn
std::string StringFormater::stOpn ="{" private
Definition at line 24 of file stringFormater.h.
Referenced by setOpen(), and start().
tl
std::string StringFormater::tl ="" private
Definition at line 18 of file stringFormater.h.
Referenced by end(), and tail().
tplCls
std::string StringFormater::tplCls =")" private
Definition at line 21 of file stringFormater.h.
Referenced by tupleClose().
tplOpn
std::string StringFormater::tplOpn ="(" private
Definition at line 20 of file stringFormater.h.
Referenced by tupleOpen().
tplSprtr
std::string StringFormater::tplSprtr ="" private
Definition at line 23 of file stringFormater.h.
Referenced by tupleSeparator().
vlSprtr
std::string StringFormater::vlSprtr =";" private
Definition at line 22 of file stringFormater.h.
Referenced by valueSeparator().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/stringFormater.h