DynComm: R-CRAN/src/DynCommRcpp.cpp File Reference
DynCommRcpp.cpp File Reference
#include "base/Cpp/defines.h"
#include "base/Cpp/DynCommBase.h"
Classes
class DummyEnum
class DummyAlgorithm
class DummyQuality
class DynCommRcpp
Functions
RCPP_MODULE (DynCommRcppModule)
Function Documentation
RCPP_MODULE()
RCPP_MODULE (DynCommRcppModule)
Definition at line 338 of file DynCommRcpp.cpp.
References DynCommRcpp::addRemoveEdgesFile(), DynCommRcpp::addRemoveEdgesMatrix(), Criterion::BALMOD, DynCommRcpp::communities(), DynCommRcpp::community(), DynCommRcpp::communityCount(), DynCommRcpp::communityEdgeWeight(), DynCommRcpp::communityInnerEdgesWeight(), DynCommRcpp::communityMappingFile(), DynCommRcpp::communityMappingMatrix(), DynCommRcpp::communityNeighbours(), DynCommRcpp::communityTotalWeight(), DynCommRcpp::communityVertexCount(), DynCommRcpp::edgeWeight(), Algorithm::LOUVAIN, Criterion::MODULARITY, DynCommRcpp::neighbours(), DynCommRcpp::quality(), DynCommRcpp::results(), DynCommRcpp::time(), DynCommRcpp::vertexCount(), DynCommRcpp::vertices(), and DynCommRcpp::verticesAll().