DynComm: R-CRAN/src/base/Cpp/edge.h File Reference
edge.h File Reference
#include <limits>
#include "stringFormatter.h"
Classes
class HalfEdge
Half edge class.
class Edge
Edge class.
Typedefs
typedef unsigned int typeVertex
typedef long double typeWeight
Functions
const Edge noEdge (noVertex, noVertex)
Variables
const typeVertex noVertex =std::numeric_limits<typeVertex>::max()
Typedef Documentation
typeVertex
typedef unsigned int typeVertex
Data type definition for a single vertex
Definition at line 24 of file edge.h.
typeWeight
typedef long double typeWeight
Data type definition for a weight
Definition at line 29 of file edge.h.
Function Documentation
noEdge()
const Edge noEdge (noVertex , noVertex)
special edge that indicates NO EDGE
Referenced by ReaderFileEdge::next(), ReaderStringEdge::next(), and ReaderMatrixEdge::next().
Variable Documentation
noVertex
const typeVertex noVertex =std::numeric_limits<typeVertex>::max()
special vertex that indicates NO VERTEX
Definition at line 260 of file edge.h.
Referenced by GraphUndirected::addEdge(), GraphUndirectedGroupable::community(), GraphUndirectedGroupable::minimumNode(), AlgorithmLouvain::neigh_comm(), GraphUndirected::neighbors(), GraphUndirected::neighborsCount(), and GraphUndirected::replace().