DynComm: R-CRAN/src/base/Cpp/graphUndirected_test.h File Reference
graphUndirected_test.h File Reference
#include "graphUndirected.h"
#include "debugging.h"
Functions
bool graphUndirected_test ()
Function Documentation
graphUndirected_test()
bool graphUndirected_test ()
Returns
true if all tests passed
Definition at line 19 of file graphUndirected_test.h.
References GraphUndirected::addEdge(), GraphUndirected::edgeCount(), GraphUndirected::maxWeight(), GraphUndirected::neighborsCount(), GraphUndirected::neighborsWeight(), GraphUndirected::removeEdge(), GraphUndirected::replace(), GraphUndirected::totalWeight(), GraphUndirected::weight(), and GraphUndirected::weighted_degree().