DynComm: R-CRAN/src/base/Cpp/graphUndirectedGroupable_test.h File Reference
graphUndirectedGroupable_test.h File Reference
#include "graphUndirectedGroupable.h"
#include "graphUndirected_test.h"
Functions
bool graphUndirectedGroupable_test ()
Function Documentation
graphUndirectedGroupable_test()
bool graphUndirectedGroupable_test ()
Returns
true if all tests passed
Definition at line 18 of file graphUndirectedGroupable_test.h.
References GraphUndirectedGroupable::addEdge(), GraphUndirectedGroupable::community(), GraphUndirectedGroupable::communityCount(), GraphUndirectedGroupable::disband(), GraphUndirected::edgeCount(), GraphUndirectedGroupable::innerEdges(), GraphUndirected::maxWeight(), GraphUndirectedGroupable::neighboringCommunitiesCount(), GraphUndirectedGroupable::neighboringCommunitiesWeight(), GraphUndirectedGroupable::neighborsCommunityCount(), GraphUndirectedGroupable::neighborsCommunityWeight(), GraphUndirected::neighborsCount(), GraphUndirected::neighborsWeight(), GraphUndirectedGroupable::removeEdge(), GraphUndirectedGroupable::replace(), GraphUndirectedGroupable::totalEdges(), GraphUndirected::totalWeight(), GraphUndirected::weight(), GraphUndirectedGroupable::weightCommunity(), and GraphUndirected::weighted_degree().