DynComm: R-CRAN/src/base/Cpp/mapReversable_test.h File Reference
mapReversable_test.h File Reference
#include "mapReversable.h"
Functions
bool mapReversable_test ()
Function Documentation
mapReversable_test()
bool mapReversable_test ()
Returns
true if all tests passed
Definition at line 17 of file mapReversable_test.h.
References MapReversable< T, U >::add(), cout, MapReversable< T, U >::remove(), MapReversable< T, U >::replace(), MapReversable< T, U >::replaceKey(), and MapReversable< T, U >::toString().