DynComm: multimap Namespace Reference
multimap Namespace Reference
Functions
template<typename T , typename U >
std::set< T > keys (std::multimap< T, U > const &m)
template<typename T , typename U >
std::set< T > values (std::multimap< T, U > const &m)
template<typename typeMultimapKey , typename typeMultimapValue , typename typeKey , typename typeValue >
std::multimap< typeMultimapKey, typeMultimapValue >::iterator find (std::multimap< typeMultimapKey, typeMultimapValue > &m, const typeKey &first, const typeValue &second)
template<typename typeMultimapKey , typename typeMultimapValue , typename typeKey , typename typeValue >
std::multimap< typeMultimapKey, typeMultimapValue >::const_iterator find (const std::multimap< typeMultimapKey, typeMultimapValue > &m, const typeKey &first, const typeValue &second)
template<typename T , typename U >
bool equalValues (const T &first, const U &second)
template<typename typeMultimapKey , typename typeMultimapValue , typename typeKey , typename typeValue >
std::multimap< typeMultimapKey, typeMultimapValue >::iterator find (std::multimap< typeMultimapKey, typeMultimapValue > &m, const typeKey &first, const typeValue &second, bool(*equalValues)(const typeMultimapValue &, const typeValue &))
template<typename typeMultimapKey , typename typeMultimapValue , typename typeKey , typename typeValue >
std::multimap< typeMultimapKey, typeMultimapValue >::const_iterator find (const std::multimap< typeMultimapKey, typeMultimapValue > &m, const typeKey &first, const typeValue &second, bool(*equalValues)(const typeMultimapValue &, const typeValue &))
template<typename T , typename U , typename std::enable_if< std::is_fundamental< T >::value &&std::is_fundamental< U >::value, T >::type = 0>
std::string toString (std::multimap< T, U > const &m, const StringFormatter &formater=defaultStringFormatter)
template<typename T , typename U >
std::multimap< T, U >::iterator & minimumValue (std::multimap< T, U > &m, const T &key)
Function Documentation
equalValues()
template<typename T , typename U > bool multimap::equalValues (const T & first, const U & second)
Default equalValues function used by the find method declared next
Parameters
first
second
Returns
Definition at line 105 of file multimapUtilities.h.
Referenced by find().
find() [1/4]
template<typename typeMultimapKey , typename typeMultimapValue , typename typeKey , typename typeValue > std::multimap<typeMultimapKey,typeMultimapValue>::iterator multimap::find (std::multimap< typeMultimapKey, typeMultimapValue > & m, const typeKey & first, const typeValue & second)
Find exact (key,value) pair in a multimap There must be an implicit type conversion between typeMultimapKey and typeKey There must be an implicit type conversion between typeMultimapValue and typeValue
Parameters
m
first
second
Returns
an iterator to the first pair found or multimap::end() if not found
Definition at line 65 of file multimapUtilities.h.
Referenced by MultimapReversable< T, U >::add(), MapReversable< typeVertex, typeCommunity >::add(), GraphUndirected::addEdge(), MultimapReversable< T, U >::remove(), MapReversable< typeVertex, typeCommunity >::remove(), GraphUndirected::removeEdge(), GraphUndirected::replace(), MapReversable< typeVertex, typeCommunity >::replaceKey(), and GraphUndirected::weight().
find() [2/4]
template<typename typeMultimapKey , typename typeMultimapValue , typename typeKey , typename typeValue > std::multimap<typeMultimapKey,typeMultimapValue>::const_iterator multimap::find (const std::multimap< typeMultimapKey, typeMultimapValue > & m, const typeKey & first, const typeValue & second)
Find exact (key,value) pair in a multimap Const version There must be an implicit type conversion between typeMultimapKey and typeKey There must be an implicit type conversion between typeMultimapValue and typeValue
Parameters
m
first
second
Returns
an iterator to the first pair found or multimap::end() if not found
Definition at line 87 of file multimapUtilities.h.
find() [3/4]
template<typename typeMultimapKey , typename typeMultimapValue , typename typeKey , typename typeValue > std::multimap<typeMultimapKey,typeMultimapValue>::iterator multimap::find (std::multimap< typeMultimapKey, typeMultimapValue > & m, const typeKey & first, const typeValue & second, bool(*)(const typeMultimapValue &, const typeValue &) equalValues)
Find exact (key,value) pair in a multimap using comparator There must be an implicit type conversion between typeMultimapKey and typeKey There must be an implicit type conversion between typeMultimapValue and typeValue if using the default comparator
Parameters
m
first
second
Returns
an iterator to the first pair found or multimap::end() if not found
Definition at line 118 of file multimapUtilities.h.
References equalValues().
find() [4/4]
template<typename typeMultimapKey , typename typeMultimapValue , typename typeKey , typename typeValue > std::multimap<typeMultimapKey,typeMultimapValue>::const_iterator multimap::find (const std::multimap< typeMultimapKey, typeMultimapValue > & m, const typeKey & first, const typeValue & second, bool(*)(const typeMultimapValue &, const typeValue &) equalValues)
Find exact (key,value) pair in a multimap using comparator There must be an implicit type conversion between typeMultimapKey and typeKey There must be an implicit type conversion between typeMultimapValue and typeValue if using the default comparator
Parameters
m
first
second
Returns
an iterator to the first pair found or multimap::end() if not found
Definition at line 139 of file multimapUtilities.h.
References equalValues().
keys()
template<typename T , typename U > std::set<T> multimap::keys (std::multimap< T, U > const & m)
Parameters
m
Returns
the unique keys of a multimap
Definition at line 33 of file multimapUtilities.h.
minimumValue()
template<typename T , typename U > std::multimap<T,U>::iterator& multimap::minimumValue (std::multimap< T, U > & m, const T & key)
get the minimum value attributed to a given key
Parameters
map
key
Returns
an iterator to the pair containing the minimum value or multimap::end() if not found
Definition at line 168 of file multimapUtilities.h.
toString()
template<typename T , typename U , typename std::enable_if< std::is_fundamental< T >::value &&std::is_fundamental< U >::value, T >::type = 0> std::string multimap::toString (std::multimap< T, U > const & m, const StringFormatter & formater = defaultStringFormatter)
Definition at line 151 of file multimapUtilities.h.
Referenced by MultimapReversable< T, U >::toString(), and MapReversable< typeVertex, typeCommunity >::toString().
values()
template<typename T , typename U > std::set<T> multimap::values (std::multimap< T, U > const & m)
Parameters
m
Returns
the unique values of a multimap
Definition at line 47 of file multimapUtilities.h.