DynComm: R-CRAN/src/base/Cpp/program.h File Reference
program.h File Reference
#include "defines.h"
#include <string>
#include <iostream>
#include <sstream>
Classes
struct ProgramParameters
Enumerations
enum LINK_WEIGHT : unsigned int { LINK_WEIGHT::WEIGHTED =1, LINK_WEIGHT::UNWEIGHTED }
Functions
void usage (const std::string &prog_name, const std::string &more)
void parse_arg (const std::string &name, const std::string &value, ProgramParameters &par)
void parse_args (int argc, char *argv[], ProgramParameters &par)
Variables
struct ProgramParameters argumentsDefault
Enumeration Type Documentation
LINK_WEIGHT
enum LINK_WEIGHT : unsigned int strong
enumeration used to indicate if the edges being added to a graph are considered as weighted (must have a weight or a default value is attributed) or unweighted (if a weight is given it is ignored).
Enumerator
WEIGHTED
UNWEIGHTED
Definition at line 30 of file program.h.
Function Documentation
parse_arg()
void parse_arg (const std::string & name, const std::string & value, ProgramParameters & par)
Parsing function for parameters passed to R
Parameters
name
value
par
Definition at line 111 of file program.h.
References ProgramParameters::alpha, ProgramParameters::directory, ProgramParameters::display_level, ProgramParameters::filename, ProgramParameters::filename_part, ProgramParameters::filename_w, ProgramParameters::id_qual, ProgramParameters::kmin, ProgramParameters::outfilename, ProgramParameters::precision, ProgramParameters::type, ProgramParameters::verbose, and WEIGHTED.
Referenced by DynCommRcpp::convertToParameters().
parse_args()
void parse_args (int argc, char * argv[], ProgramParameters & par)
Parsing function for program parameters passed to the standalone program
Parameters
argc
argv
par
Definition at line 154 of file program.h.
References ProgramParameters::alpha, ProgramParameters::directory, ProgramParameters::display_level, ProgramParameters::filename, ProgramParameters::filename_part, ProgramParameters::filename_w, ProgramParameters::id_qual, ProgramParameters::kmin, ProgramParameters::outfilename, ProgramParameters::precision, ProgramParameters::type, usage(), ProgramParameters::verbose, and WEIGHTED.
usage()
void usage (const std::string & prog_name, const std::string & more)
Usage print for standalone program
Parameters
prog_name is the name of the executable
more is a header
Definition at line 37 of file program.h.
References COUT, and exit.
Referenced by parse_args().
Variable Documentation
argumentsDefault
struct ProgramParameters argumentsDefault