DynComm: MapReversable< T, U > Class Template Reference
MapReversable< T, U > Class Template Reference
Doubly indexed map.
#include <mapReversable.h>
Public Types
typedef std::map< T, U >::const_iterator const_iterator
typedef std::pair< T, U > typePair
typedef std::multimap< U, T >::const_iterator range_iterator_const
typedef std::pair< U, T > typeRangePair
typedef std::pair< range_iterator_const, range_iterator_const > typeRange
Public Member Functions
MapReversable ()
const size_t size () const
const_iterator find (const T &key) const
std::set< T > keys () const
range_iterator_const key (const U &value) const
typeRange keys (const U &value) const
std::set< T > values () const
const_iterator value (const T &key) const
const_iterator cbegin () const
const_iterator cend () const
range_iterator_const cbeginr () const
range_iterator_const cendr () const
U operator[] (const T &key) const
bool add (const T &key, const U &value, const bool &replace=false)
bool remove (const T &first, const U &second)
bool remove (const T &first)
bool replace (const U &oldValue, const U &newValue)
bool replaceKey (const T &oldKey, const T &newKey)
std::string toString (const StringFormatter &sf=defaultStringFormatter) const
Private Types
typedef std::map< T, U >::iterator iterator
typedef std::multimap< U, T >::iterator range_iterator
Private Attributes
std::map< T, U > m
std::multimap< U, T > r
Detailed Description
template<typename T, typename U>
class MapReversable< T, U >
Doubly indexed map.
Class that implements a map in which the values are also indexed. Unlike an ordinary std::map which is indexed by key only, this map is also indexed by value. It internally uses a std::multimap to achieve this.
Author
poltergeist0
Date
2018-08-19
Definition at line 44 of file mapReversable.h.
Member Typedef Documentation
const_iterator
template<typename T, typename U> typedef std::map<T,U>::const_iterator MapReversable< T, U >::const_iterator
Definition at line 54 of file mapReversable.h.
iterator
template<typename T, typename U> typedef std::map<T,U>::iterator MapReversable< T, U >::iterator private
Definition at line 49 of file mapReversable.h.
range_iterator
template<typename T, typename U> typedef std::multimap<U,T>::iterator MapReversable< T, U >::range_iterator private
Definition at line 50 of file mapReversable.h.
range_iterator_const
template<typename T, typename U> typedef std::multimap<U,T>::const_iterator MapReversable< T, U >::range_iterator_const
Definition at line 56 of file mapReversable.h.
typePair
template<typename T, typename U> typedef std::pair<T,U> MapReversable< T, U >::typePair
Definition at line 55 of file mapReversable.h.
typeRange
template<typename T, typename U> typedef std::pair<range_iterator_const,range_iterator_const> MapReversable< T, U >::typeRange
Definition at line 58 of file mapReversable.h.
typeRangePair
template<typename T, typename U> typedef std::pair<U,T> MapReversable< T, U >::typeRangePair
Definition at line 57 of file mapReversable.h.
Constructor & Destructor Documentation
MapReversable()
template<typename T, typename U> MapReversable< T, U >::MapReversable () inline
default constructor
Definition at line 63 of file mapReversable.h.
Member Function Documentation
add()
template<typename T, typename U> bool MapReversable< T, U >::add (const T & key, const U & value, const bool & replace = false) inline
Add a (key, value) pair to the map
Parameters
key
value
replace,if true and key exists, replaces the value otherwise fails. If false and key exists fails.
Returns
true if insertion succeeds
Definition at line 145 of file mapReversable.h.
Referenced by GraphUndirectedGroupable::addEdge(), DynCommBase::addRemoveEdges(), and GraphUndirectedGroupable::community().
cbegin()
template<typename T, typename U> const_iterator MapReversable< T, U >::cbegin () const inline
Returns
a constant iterator to the beginning of the map
Definition at line 106 of file mapReversable.h.
Referenced by GraphUndirectedGroupable::communitiesToGraph(), and DynCommBase::communityMapping().
cbeginr()
template<typename T, typename U> range_iterator_const MapReversable< T, U >::cbeginr () const inline
Returns
a constant iterator to the beginning of the multimap
Definition at line 117 of file mapReversable.h.
cend()
template<typename T, typename U> const_iterator MapReversable< T, U >::cend () const inline
Returns
a constant iterator to the end of the map
Definition at line 111 of file mapReversable.h.
Referenced by GraphUndirectedGroupable::communitiesToGraph(), GraphUndirectedGroupable::community(), DynCommBase::communityMapping(), and GraphUndirectedGroupable::replace().
cendr()
template<typename T, typename U> range_iterator_const MapReversable< T, U >::cendr () const inline
Returns
a constant iterator to the end of the multimap
Definition at line 122 of file mapReversable.h.
find()
template<typename T, typename U> const_iterator MapReversable< T, U >::find (const T & key) const inline
Find the value attributed to a given key
Parameters
key
Returns
a constant iterator that points to the pair that holds the (key, value) or cend() if not found
Definition at line 72 of file mapReversable.h.
Referenced by GraphUndirectedGroupable::community(), and MapReversable< typeVertex, typeCommunity >::value().
key()
template<typename T, typename U> range_iterator_const MapReversable< T, U >::key (const U & value) const inline
get all the keys that have a given value
Parameters
value
Returns
a pair of constant range iterators pointing, respectively, to the beginning and to the end of the range of keys that holds the given value
Definition at line 85 of file mapReversable.h.
keys() [1/2]
template<typename T, typename U> std::set<T> MapReversable< T, U >::keys () const inline
Compatibility function with multimap since in a map all keys are unique
Returns
all unique keys in the map
Definition at line 78 of file mapReversable.h.
Referenced by GraphUndirectedGroupable::community(), GraphUndirectedGroupable::disband(), MapReversable< typeVertex, typeCommunity >::keys(), GraphUndirectedGroupable::minimumNode(), and GraphUndirectedGroupable::vertices().
keys() [2/2]
template<typename T, typename U> typeRange MapReversable< T, U >::keys (const U & value) const inline
get all the keys that have a given value
Parameters
value
Returns
a pair of constant range iterators pointing, respectively, to the beginning and to the end of the range of keys that holds the given value
Definition at line 92 of file mapReversable.h.
operator[]()
template<typename T, typename U> U MapReversable< T, U >::operator[] (const T & key) const inline
Get value associated with key. If the key entry does not exists it is created with the default value
Parameters
key
Returns
either the existing value or the newly created value
Definition at line 129 of file mapReversable.h.
remove() [1/2]
template<typename T, typename U> bool MapReversable< T, U >::remove (const T & first, const U & second) inline
remove a (key,value) pair
Parameters
first
second
Returns
true if the element existed otherwise false
Definition at line 175 of file mapReversable.h.
Referenced by GraphUndirectedGroupable::communitiesToGraph(), and GraphUndirectedGroupable::removeEdge().
remove() [2/2]
template<typename T, typename U> bool MapReversable< T, U >::remove (const T & first) inline
remove a (key,value) pair
Parameters
first
Returns
true if the element existed otherwise false
Definition at line 194 of file mapReversable.h.
replace()
template<typename T, typename U> bool MapReversable< T, U >::replace (const U & oldValue, const U & newValue) inline
Replace all occurrences of oldValue by newValue
Parameters
oldValue
newValue
Returns
true if replacement succeeded
Definition at line 214 of file mapReversable.h.
Referenced by MapReversable< typeVertex, typeCommunity >::add(), GraphUndirectedGroupable::replace(), and GraphUndirectedGroupable::replaceCommunity().
replaceKey()
template<typename T, typename U> bool MapReversable< T, U >::replaceKey (const T & oldKey, const T & newKey) inline
Replace all occurrences of oldKey by newKey
Parameters
oldKey
newKey
Returns
true if replacement succeeded
Definition at line 239 of file mapReversable.h.
Referenced by GraphUndirectedGroupable::replace().
size()
template<typename T, typename U> const size_t MapReversable< T, U >::size () const inline
Definition at line 65 of file mapReversable.h.
Referenced by DynCommBase::communityMapping().
toString()
template<typename T, typename U> std::string MapReversable< T, U >::toString (const StringFormatter & sf = defaultStringFormatter) const inline
Returns
a string representation of this map list and reverse list
Definition at line 255 of file mapReversable.h.
Referenced by GraphUndirectedGroupable::toString().
value()
template<typename T, typename U> const_iterator MapReversable< T, U >::value (const T & key) const inline
Definition at line 100 of file mapReversable.h.
Referenced by DynCommBase::communityMapping(), and GraphUndirectedGroupable::replace().
values()
template<typename T, typename U> std::set<T> MapReversable< T, U >::values () const inline
Returns
all unique values in the map
Definition at line 98 of file mapReversable.h.
Referenced by MapReversable< typeVertex, typeCommunity >::values().
Member Data Documentation
m
template<typename T, typename U> std::map<T,U> MapReversable< T, U >::m private
Definition at line 46 of file mapReversable.h.
r
template<typename T, typename U> std::multimap<U,T> MapReversable< T, U >::r private
Definition at line 47 of file mapReversable.h.
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/mapReversable.h