DynComm: Time::TimeKeeper Class Reference
Time::TimeKeeper Class Reference
Simple class used to keep track of elapsed time.
#include <timeFunctions.h>
Public Member Functions
TimeKeeper (uint64 time=0)
uint64 set (uint64 time=0, bool update=true)
uint64 get (const uint64 &time=0) const
Private Member Functions
uint64 validateBaseTime (const uint64 &time) const
uint64 validateTime (const uint64 &time) const
Private Attributes
uint64 r
uint64 t
Detailed Description
Simple class used to keep track of elapsed time.
keeps track of elapsed time since given time or epoch, if time=0
Author
poltergeist0
Date
2018-11-12
Definition at line 77 of file timeFunctions.h.
Constructor & Destructor Documentation
TimeKeeper()
Time::TimeKeeper::TimeKeeper (uint64 time = 0) inline
Definition at line 102 of file timeFunctions.h.
Member Function Documentation
get()
uint64 Time::TimeKeeper::get (const uint64 & time = 0) const inline
get current time or the elapsed time regarding the saved reference time or translate a time to the configured time referential If there is no base time and the given time is zero, return the current time (time since epoch) If there is no base time and the given time is not zero, return the elapsed time since the last call to set or the constructor If there is base time and the given time is zero, return the elapsed time since reference time in regard to the configured base time If there is base time and the given time is not zero, return the time difference of the given time compared to the reference time in regard to the configured base time
Parameters
time
Returns
Definition at line 124 of file timeFunctions.h.
References Time::currentTime(), r, t, and validateTime().
set()
uint64 Time::TimeKeeper::set (uint64 time = 0, bool update = true) inline
set base (intended) time and possibly update the reference time
Definition at line 106 of file timeFunctions.h.
References Time::currentTime(), and validateBaseTime().
validateBaseTime()
uint64 Time::TimeKeeper::validateBaseTime (const uint64 & time) const inline private
Definition at line 89 of file timeFunctions.h.
Referenced by set().
validateTime()
uint64 Time::TimeKeeper::validateTime (const uint64 & time) const inline private
Definition at line 95 of file timeFunctions.h.
Referenced by get().
Member Data Documentation
r
uint64 Time::TimeKeeper::r private
Definition at line 82 of file timeFunctions.h.
Referenced by get().
t
uint64 Time::TimeKeeper::t private
Definition at line 87 of file timeFunctions.h.
Referenced by get().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/timeFunctions.h