DynComm: Criterion Class Reference
Criterion Class Reference
Aggregator class for all criterion.
#include <criterion.h>
Public Types
enum CRITERION : unsigned int { CRITERION::MODULARITY =1, CRITERION::BALMOD }
Public Member Functions
Criterion (const GraphUndirectedGroupable &graph, const CRITERION &criterion, const ProgramParameters &parameters=argumentsDefault)
~Criterion ()
typeCriterion gain (const typeVertex &vertex, const typeCommunity &comm) const
typeCriterion quality () const
CRITERION type () const
Public Member Functions inherited from CriterionInterface
virtual ~CriterionInterface ()
Private Attributes
const CRITERION crtrn
CriterionModularity criterionModularity
CriterionBalMod criterionBalMod
Detailed Description
Aggregator class for all criterion.
It is a simple class that only instantiates all criterion and dispatches function calls to the correct one.
Author
poltergeist0
Date
2018-08-19
Definition at line 46 of file criterion.h.
Member Enumeration Documentation
CRITERION
enum Criterion::CRITERION : unsigned int strong
Enumeration with the list of supported criterion for algorithms implemented in C++. This enumeration must start at 1 since this code is used in R and R indexing (for arrays, etc) starts at 1 instead of 0. Otherwise C++ would assign the first criterion a 0.
Enumerator
MODULARITY
BALMOD
Definition at line 60 of file criterion.h.
Constructor & Destructor Documentation
Criterion()
Criterion::Criterion (const GraphUndirectedGroupable & graph, const CRITERION & criterion, const ProgramParameters & parameters = argumentsDefault) inline
Constructor
Parameters
graph
criterion
parameters
Definition at line 90 of file criterion.h.
~Criterion()
Criterion::~Criterion () inline
Destructor
Definition at line 108 of file criterion.h.
Member Function Documentation
gain()
typeCriterion Criterion::gain (const typeVertex & vertex, const typeCommunity & comm) const inline virtual
compute the quality obtained if the given vertex was moved from its current community to the given community
Parameters
vertex
comm new potential community for given vertex
Returns
the quality, which may be positive or negative
Implements CriterionInterface.
Definition at line 118 of file criterion.h.
References BALMOD, CriterionBalMod::gain(), CriterionModularity::gain(), and MODULARITY.
Referenced by AlgorithmLouvain::gain().
quality()
typeCriterion Criterion::quality () const inline virtual
compute the quality of the current partition scheme
Returns
the quality value
Implements CriterionInterface.
Definition at line 136 of file criterion.h.
References BALMOD, MODULARITY, CriterionBalMod::quality(), and CriterionModularity::quality().
Referenced by DynCommBase::quality(), and AlgorithmLouvain::quality().
type()
CRITERION Criterion::type () const inline
Returns
the chosen criterion
Definition at line 153 of file criterion.h.
References crtrn.
Member Data Documentation
criterionBalMod
CriterionBalMod Criterion::criterionBalMod private
Definition at line 73 of file criterion.h.
criterionModularity
CriterionModularity Criterion::criterionModularity private
Definition at line 72 of file criterion.h.
crtrn
const CRITERION Criterion::crtrn private
Definition at line 67 of file criterion.h.
Referenced by type().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/criterion.h