DynComm: StringFormatter Class Reference
StringFormatter Class Reference
StringFormatter class.
#include <stringFormatter.h>
Public Member Functions
StringFormatter ()
StringFormatter (const StringFormatter &copy, const bool &autoIndent=true)
StringFormatter (const StringFormatter &copy, const int indent)
Copy constructor with indentation level.
StringFormatter operator() (const int indent) const
const std::string & header () const
void header (const std::string &header)
const std::string & setClose () const
void setClose (const std::string &setClose)
const std::string & setOpen () const
void setOpen (const std::string &setOpen)
const std::string & tail () const
void tail (const std::string &tail)
const std::string & tupleClose () const
void tupleClose (const std::string &tupleClose)
const std::string & tupleOpen () const
void tupleOpen (const std::string &tupleOpen)
const std::string & tupleSeparator () const
void tupleSeparator (const std::string &tupleSeparator)
const std::string & valueSeparator () const
void valueSeparator (const std::string &valueSeparator)
std::string indent () const
std::stringstream & start (std::stringstream &ss, const bool &set=false) const
std::string start (const bool &set=false) const
std::stringstream & end (std::stringstream &ss, const bool &set=false) const
End writing to string stream.
std::string end (const bool &set=false) const
End writing to string.
std::stringstream & build (std::stringstream &ss, const std::string &message)
Build a formatted message.
std::string build (const std::string &message)
Build a formatted message.
StringFormatter & operator++ ()
StringFormatter & operator-- ()
bool isDefault () const
Private Attributes
unsigned int indentLevel =0
std::string hdr =""
std::string tl =""
bool lnBrk =true
std::string tplOpn ="("
std::string tplCls =")"
std::string vlSprtr =";"
std::string tplSprtr =""
std::string stOpn ="{"
std::string stCls ="}"
Detailed Description
StringFormatter class.
This class provides a generic, easy way to format the insertion of header, tail, sets, tuples, indentation and new lines in strings. It is specially useful in repetitive situations, as an example, when the same header and tail must be set in every line of an output.
Author
poltergeist0
Date
2018-10-08
Definition at line 36 of file stringFormatter.h.
Constructor & Destructor Documentation
StringFormatter() [1/3]
StringFormatter::StringFormatter () inline
default constructor
Definition at line 54 of file stringFormatter.h.
Referenced by operator()().
StringFormatter() [2/3]
StringFormatter::StringFormatter (const StringFormatter & copy, const bool & autoIndent = true) inline
Copy constructor
Parameters
copy
autoIndent if true indents the contents by one tabulation relative to the original
Definition at line 66 of file stringFormatter.h.
References isDefault().
StringFormatter() [3/3]
StringFormatter::StringFormatter (const StringFormatter & copy, const int indent) inline
Copy constructor with indentation level.
Indents the contents by the given value relative to the original.
If the given value is negative, it removes indentations until it either becomes zero or equal to original indentation level minus given level.
Parameters
copy
indent is the indentation level to add/subtract
Definition at line 88 of file stringFormatter.h.
References indent().
Member Function Documentation
build() [1/2]
std::stringstream& StringFormatter::build (std::stringstream & ss, const std::string & message) inline
Build a formatted message.
Automatically calls the start function, prints the message and calls the end function.
Parameters
ss
message
Returns
Definition at line 286 of file stringFormatter.h.
References end(), and start().
Referenced by build(), AlgorithmBase::toString(), MapReversable< typeVertex, typeCommunity >::toString(), AlgorithmLouvain::toString(), and GraphUndirectedGroupable::toString().
build() [2/2]
std::string StringFormatter::build (const std::string & message) inline
Build a formatted message.
Automatically calls the start function, prints the message and calls the end function.
Parameters
message
Returns
Definition at line 301 of file stringFormatter.h.
References build().
end() [1/2]
std::stringstream& StringFormatter::end (std::stringstream & ss, const bool & set = false) const inline
End writing to string stream.
If the set argument was true when the start function was called, the set argument in this function should also be true unless the set was closed manually.
Parameters
ss
set if true automatically closes a set
Returns
Definition at line 251 of file stringFormatter.h.
References stCls, and tl.
Referenced by build(), end(), and GraphUndirected::toString().
end() [2/2]
std::string StringFormatter::end (const bool & set = false) const inline
End writing to string.
If the set argument was true when the start function was called, the set argument in this function should also be true unless the set was closed manually.
Parameters
set if true automatically closes a set
Returns
Definition at line 271 of file stringFormatter.h.
References end().
header() [1/2]
const std::string& StringFormatter::header () const inline
Returns
the currently set header
Definition at line 110 of file stringFormatter.h.
References hdr.
Referenced by AlgorithmBase::toString(), MapReversable< typeVertex, typeCommunity >::toString(), GraphUndirected::toString(), AlgorithmLouvain::toString(), and GraphUndirectedGroupable::toString().
header() [2/2]
void StringFormatter::header (const std::string & header) inline
Set a new header
Parameters
header
Definition at line 116 of file stringFormatter.h.
References header().
Referenced by header().
indent()
std::string StringFormatter::indent () const inline
Returns
a string with the current indentation level
Definition at line 207 of file stringFormatter.h.
Referenced by start(), and StringFormatter().
isDefault()
bool StringFormatter::isDefault () const
Returns
true if this object is the default string formatter object
Definition at line 336 of file stringFormatter.h.
References defaultStringFormatter.
Referenced by operator--(), and StringFormatter().
operator()()
StringFormatter StringFormatter::operator() (const int indent) const inline
Parameters
indent is the indentation to add/subtract to copy
Returns
copy of this StringFormatter object
Definition at line 102 of file stringFormatter.h.
References StringFormatter().
operator++()
StringFormatter& StringFormatter::operator++ () inline
Increment the current indentation level
Returns
this object
Definition at line 310 of file stringFormatter.h.
operator--()
StringFormatter& StringFormatter::operator-- () inline
Decrement the current indentation level
Returns
this object
Definition at line 319 of file stringFormatter.h.
References defaultStringFormatter, and isDefault().
setClose() [1/2]
const std::string& StringFormatter::setClose () const inline
Returns
the string that represents closing of a set
Definition at line 122 of file stringFormatter.h.
References stCls.
Referenced by GraphUndirected::toString().
setClose() [2/2]
void StringFormatter::setClose (const std::string & setClose) inline
Set the string that represents closing of a set
Parameters
setClose
Definition at line 128 of file stringFormatter.h.
References setClose().
Referenced by setClose().
setOpen() [1/2]
const std::string& StringFormatter::setOpen () const inline
Returns
the string that represents opening of a set
Definition at line 134 of file stringFormatter.h.
References stOpn.
Referenced by GraphUndirected::toString().
setOpen() [2/2]
void StringFormatter::setOpen (const std::string & setOpen) inline
Set the string that represents opening of a set
Parameters
setOpen
Definition at line 140 of file stringFormatter.h.
References setOpen().
Referenced by setOpen().
start() [1/2]
std::stringstream& StringFormatter::start (std::stringstream & ss, const bool & set = false) const inline
Start writing to string stream
Parameters
ss
set if true automatically opens a set
Returns
Definition at line 218 of file stringFormatter.h.
References hdr, indent(), and stOpn.
Referenced by build(), start(), and GraphUndirected::toString().
start() [2/2]
std::string StringFormatter::start (const bool & set = false) const inline
Start writing to string
Parameters
set if true automatically opens a set
Returns
Definition at line 235 of file stringFormatter.h.
References start().
tail() [1/2]
const std::string& StringFormatter::tail () const inline
Returns
the currently set tail
Definition at line 146 of file stringFormatter.h.
References tl.
tail() [2/2]
void StringFormatter::tail (const std::string & tail) inline
Set a new tail
Parameters
tail
Definition at line 152 of file stringFormatter.h.
References tail().
Referenced by tail().
tupleClose() [1/2]
const std::string& StringFormatter::tupleClose () const inline
Returns
the string that represents closing of a tuple
Definition at line 159 of file stringFormatter.h.
References tplCls.
Referenced by GraphUndirected::toString().
tupleClose() [2/2]
void StringFormatter::tupleClose (const std::string & tupleClose) inline
Set the string that represents closing of a tuple
Parameters
tupleClose
Definition at line 165 of file stringFormatter.h.
References tupleClose().
Referenced by tupleClose().
tupleOpen() [1/2]
const std::string& StringFormatter::tupleOpen () const inline
Returns
the string that represents opening of a tuple
Definition at line 171 of file stringFormatter.h.
References tplOpn.
Referenced by GraphUndirected::toString().
tupleOpen() [2/2]
void StringFormatter::tupleOpen (const std::string & tupleOpen) inline
Set the string that represents opening of a tuple
Parameters
tupleOpen
Definition at line 177 of file stringFormatter.h.
References tupleOpen().
Referenced by tupleOpen().
tupleSeparator() [1/2]
const std::string& StringFormatter::tupleSeparator () const inline
Returns
the string that represents a tuple separator
Definition at line 183 of file stringFormatter.h.
References tplSprtr.
tupleSeparator() [2/2]
void StringFormatter::tupleSeparator (const std::string & tupleSeparator) inline
Set the string that represents a tuple separator
Parameters
tupleSeparator
Definition at line 189 of file stringFormatter.h.
References tupleSeparator().
Referenced by tupleSeparator().
valueSeparator() [1/2]
const std::string& StringFormatter::valueSeparator () const inline
Returns
the string that represents a value separator
Definition at line 195 of file stringFormatter.h.
References vlSprtr.
Referenced by GraphUndirected::toString().
valueSeparator() [2/2]
void StringFormatter::valueSeparator (const std::string & valueSeparator) inline
Set the string that represents a value separator
Parameters
valueSeparator
Definition at line 201 of file stringFormatter.h.
References valueSeparator().
Referenced by valueSeparator().
Member Data Documentation
hdr
std::string StringFormatter::hdr ="" private
Definition at line 39 of file stringFormatter.h.
Referenced by header(), and start().
indentLevel
unsigned int StringFormatter::indentLevel =0 private
Definition at line 38 of file stringFormatter.h.
lnBrk
bool StringFormatter::lnBrk =true private
Definition at line 41 of file stringFormatter.h.
stCls
std::string StringFormatter::stCls ="}" private
Definition at line 47 of file stringFormatter.h.
Referenced by end(), and setClose().
stOpn
std::string StringFormatter::stOpn ="{" private
Definition at line 46 of file stringFormatter.h.
Referenced by setOpen(), and start().
tl
std::string StringFormatter::tl ="" private
Definition at line 40 of file stringFormatter.h.
Referenced by end(), and tail().
tplCls
std::string StringFormatter::tplCls =")" private
Definition at line 43 of file stringFormatter.h.
Referenced by tupleClose().
tplOpn
std::string StringFormatter::tplOpn ="(" private
Definition at line 42 of file stringFormatter.h.
Referenced by tupleOpen().
tplSprtr
std::string StringFormatter::tplSprtr ="" private
Definition at line 45 of file stringFormatter.h.
Referenced by tupleSeparator().
vlSprtr
std::string StringFormatter::vlSprtr =";" private
Definition at line 44 of file stringFormatter.h.
Referenced by valueSeparator().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/stringFormatter.h