DynComm: WriterInterface Class Reference
WriterInterface Class Reference abstract
Interface for a simple stream forward writer.
#include <writer.h>
Public Types
enum WRITETYPE : unsigned int { WRITETYPE::LINE =1, WRITETYPE::VALUE, WRITETYPE::COMMENT }
Public Member Functions
virtual ~WriterInterface ()
virtual bool isReady ()=0
virtual bool write (const std::string &object, const WRITETYPE &type=WRITETYPE::VALUE)=0
virtual std::string status ()=0
Detailed Description
Interface for a simple stream forward writer.
Writers that implement this interface can not write backwards, only append to the end.
Author
poltergeist0
Date
2019-02-06
Definition at line 38 of file writer.h.
Member Enumeration Documentation
WRITETYPE
enum WriterInterface::WRITETYPE : unsigned int strong
Enumeration of the types of objects that can be written
Enumerator
LINE
VALUE
COMMENT
Definition at line 43 of file writer.h.
Constructor & Destructor Documentation
~WriterInterface()
virtual WriterInterface::~WriterInterface () inline virtual
Definition at line 45 of file writer.h.
References isReady(), status(), VALUE, and write().
Member Function Documentation
isReady()
virtual bool WriterInterface::isReady () pure virtual
Returns
true if the sink is ready to be written
Implemented in WriterFile, and WriterStream.
Referenced by ~WriterInterface().
status()
virtual std::string WriterInterface::status () pure virtual
Returns
either an ok message or an error message
Implemented in WriterFile, and WriterStream.
Referenced by ~WriterInterface().
write()
virtual bool WriterInterface::write (const std::string & object, const WRITETYPE & type = WRITETYPE::VALUE) pure virtual
Parameters
object
type
Returns
Implemented in WriterFile, and WriterStream.
Referenced by DynCommBase::communityMapping(), and ~WriterInterface().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/writer.h