DynComm: DynCommBase Class Reference
DynCommBase Class Reference
Dynamic Communities base class.
#include <DynCommBase.h>
Public Member Functions
DynCommBase ()=delete
DynCommBase (Algorithm::ALGORITHM algorithm=Algorithm::ALGORITHM::LOUVAIN, const Criterion::CRITERION &quality=Criterion::CRITERION::MODULARITY, ProgramParameters &algorithmParameters=argumentsDefault)
bool addRemoveEdges (ReaderInterface< Edge > *reader)
typeCriterion quality () const
int communityCount () const
typeCommunities communities () const
typeWeight communitiesEdgeCount () const
typeLinksRangeConst communityNeighbours (typeCommunity community) const
typeWeight communityInnerEdgesWeight (typeCommunity community) const
typeWeight communityTotalWeight (typeCommunity community) const
typeWeight communityEdgeWeight (typeCommunity source, typeCommunity destination) const
int communityVertexCount (typeCommunity community) const
typeCommunity community (typeVertex vertex) const
unsigned int vertexCount () const
typeVertexList vertices () const
typeVertexList vertices (typeCommunity community) const
typeWeight edgeCount () const
bool communityMapping (WriterInterface *writer, bool communityFirst=true, bool differential=true) const
typeLinksRangeConst neighbours (typeVertex vertex) const
Get the neighbours of a vertex.
typeWeight weight (const typeVertex &source, const typeVertex &destination) const
uint64 time (bool accumulated=true) const
Private Attributes
Algorithm algrthm
GraphUndirectedGroupable grph
Criterion qlt
ProgramParameters prmtrs
uint64 timeTotal =0
uint64 timeStart =0
uint64 timeProcessing =0
typeCommunityList oldCommunities
Additional Inherited Members
Private Member Functions inherited from DynCommBaseInterface
virtual ~DynCommBaseInterface ()
Detailed Description
Dynamic Communities base class.
Simple class that only converts between data types and dispatches function calls to the correct object (graph, criterion or algorithm).
Author
poltergeist0
Date
2019-02-02
Definition at line 42 of file DynCommBase.h.
Constructor & Destructor Documentation
DynCommBase() [1/2]
DynCommBase::DynCommBase () delete
Default constructor not acceptable. Must be passed at least the chosen algorithm and the graph
DynCommBase() [2/2]
DynCommBase::DynCommBase (Algorithm::ALGORITHM algorithm = Algorithm::ALGORITHM::LOUVAIN, const Criterion::CRITERION & quality = Criterion::CRITERION::MODULARITY, ProgramParameters & algorithmParameters = argumentsDefault) inline
Constructor
Definition at line 81 of file DynCommBase.h.
Member Function Documentation
addRemoveEdges()
bool DynCommBase::addRemoveEdges (ReaderInterface< Edge > * reader) inline virtual
Function to add and remove edges from the graph. Any edge with a weight different from zero is inserted. Any edge with a weight of exactly zero is removed.
Returns
true if adding/removing succeeded
Implements DynCommBaseInterface.
Definition at line 102 of file DynCommBase.h.
References MapReversable< T, U >::add(), Algorithm::addRemoveEdges(), GraphUndirectedGroupable::community(), Time::currentTime(), GraphUndirected::getVertices(), timeProcessing, and timeStart.
Referenced by DynCommRcpp::addRemoveEdgesFile(), and DynCommRcpp::addRemoveEdgesMatrix().
communities()
typeCommunities DynCommBase::communities () const inline virtual
Returns
the list of all existing communities
Implements DynCommBaseInterface.
Definition at line 135 of file DynCommBase.h.
References GraphUndirectedGroupable::communities().
Referenced by DynCommRcpp::communities().
communitiesEdgeCount()
typeWeight DynCommBase::communitiesEdgeCount () const inline
Get the number of community to community edges in the graph
Returns
the number of edges
Definition at line 144 of file DynCommBase.h.
References GraphUndirectedGroupable::communitiesEdgeCount().
Referenced by DynCommRcpp::communitiesEdgeCount().
community()
typeCommunity DynCommBase::community (typeVertex vertex) const inline virtual
Parameters
node
Returns
the community of the given vertex or a special community of noGRoup if the vertex does not exist
Implements DynCommBaseInterface.
Definition at line 210 of file DynCommBase.h.
References GraphUndirectedGroupable::community().
Referenced by DynCommRcpp::community(), and DynCommRcpp::communityMappingMatrix().
communityCount()
int DynCommBase::communityCount () const inline virtual
Returns
the number of existing communities
Implements DynCommBaseInterface.
Definition at line 128 of file DynCommBase.h.
References GraphUndirectedGroupable::communityCount().
Referenced by DynCommRcpp::communityCount().
communityEdgeWeight()
typeWeight DynCommBase::communityEdgeWeight (typeCommunity source, typeCommunity destination) const inline virtual
Get the weight of the edge form by two communities
Parameters
source community
destination community
Returns
the weight of the edge
Implements DynCommBaseInterface.
Definition at line 186 of file DynCommBase.h.
References GraphUndirectedGroupable::weightCommunity().
Referenced by DynCommRcpp::communityEdgeWeight().
communityInnerEdgesWeight()
typeWeight DynCommBase::communityInnerEdgesWeight (typeCommunity community) const inline virtual
Get the sum of the weights of all edges of the given community where both vertices of an edge belong to the given community.
Parameters
community
Returns
the sum of the weights of all inner edges
Implements DynCommBaseInterface.
Definition at line 165 of file DynCommBase.h.
References GraphUndirectedGroupable::innerEdges().
Referenced by DynCommRcpp::communityInnerEdgesWeight().
communityMapping()
bool DynCommBase::communityMapping (WriterInterface * writer, bool communityFirst = true, bool differential = true) const inline virtual
Get a snapshot of the current community mapping. If communityFirst is true the result will be one community per line with each line being a community followed by a list of vertices. If false, the result will be a vertex per line with each line being a single vertex and a single community. The differential parameter will probably be moved inside the writer as a parameter
Parameters
writer
communityFirst if true returns a community followed by a list of vertices, otherwise a vertex and its community
differential return only what changed in the last iteration of the algorithm
Returns
true if the operation succeeded
Implements DynCommBaseInterface.
Definition at line 263 of file DynCommBase.h.
References MapReversable< T, U >::cbegin(), MapReversable< T, U >::cend(), GraphUndirectedGroupable::communities(), GraphUndirectedGroupable::community(), GraphUndirected::getVertices(), WriterInterface::LINE, MapReversable< T, U >::size(), WriterInterface::VALUE, MapReversable< T, U >::value(), GraphUndirected::vertexCount(), vertices(), and WriterInterface::write().
Referenced by DynCommRcpp::communityMappingFile().
communityNeighbours()
typeLinksRangeConst DynCommBase::communityNeighbours (typeCommunity community) const inline virtual
Get the communities that are neighbours of the given community
Parameters
community
Returns
the neighbouring communities
Implements DynCommBaseInterface.
Definition at line 154 of file DynCommBase.h.
References GraphUndirectedGroupable::neighbouringCommunities().
Referenced by DynCommRcpp::communityNeighbours().
communityTotalWeight()
typeWeight DynCommBase::communityTotalWeight (typeCommunity community) const inline virtual
Get the sum of the weights of all edges of the given community.
Parameters
community
Returns
the sum of the weights of all edges
Implements DynCommBaseInterface.
Definition at line 175 of file DynCommBase.h.
References GraphUndirectedGroupable::totalEdges().
Referenced by DynCommRcpp::communityTotalWeight().
communityVertexCount()
int DynCommBase::communityVertexCount (typeCommunity community) const inline virtual
Get the number of vertices in the given community
Parameters
community
Returns
the number of vertices
Implements DynCommBaseInterface.
Definition at line 196 of file DynCommBase.h.
References GraphUndirectedGroupable::vertices().
Referenced by DynCommRcpp::communityVertexCount().
edgeCount()
typeWeight DynCommBase::edgeCount () const inline
Get the number of vertex to vertex edges in the graph
Returns
the number of edges
Definition at line 246 of file DynCommBase.h.
References GraphUndirected::edgeCount().
Referenced by DynCommRcpp::edgeCount().
neighbours()
typeLinksRangeConst DynCommBase::neighbours (typeVertex vertex) const inline virtual
Get the neighbours of a vertex.
The pair can change between calls if the Indexed edge list is modified.
Parameters
vertex
Returns
pointers to the first and last neighbour of the vertex
Implements DynCommBaseInterface.
Definition at line 394 of file DynCommBase.h.
References GraphUndirected::neighbours().
Referenced by DynCommRcpp::neighbours().
quality()
typeCriterion DynCommBase::quality () const inline virtual
Returns
the current quality measure of the community mapping on the graph
Implements DynCommBaseInterface.
Definition at line 121 of file DynCommBase.h.
References Criterion::quality().
Referenced by DynCommRcpp::quality().
time()
uint64 DynCommBase::time (bool accumulated = true) const inline virtual
Returns
the total processing time in nanoseconds
Implements DynCommBaseInterface.
Definition at line 409 of file DynCommBase.h.
References timeProcessing, and timeTotal.
Referenced by DynCommRcpp::results(), and DynCommRcpp::time().
vertexCount()
unsigned int DynCommBase::vertexCount () const inline virtual
Returns
the number of vertices in the graph
Implements DynCommBaseInterface.
Definition at line 217 of file DynCommBase.h.
References GraphUndirected::vertexCount().
Referenced by DynCommRcpp::communityMappingMatrix(), and DynCommRcpp::vertexCount().
vertices() [1/2]
typeVertexList DynCommBase::vertices () const inline virtual
Returns
a constant set with all vertices
Implements DynCommBaseInterface.
Definition at line 224 of file DynCommBase.h.
References GraphUndirected::getVertices().
Referenced by communityMapping(), DynCommRcpp::communityMappingMatrix(), DynCommRcpp::vertices(), and DynCommRcpp::verticesAll().
vertices() [2/2]
typeVertexList DynCommBase::vertices (typeCommunity community) const inline virtual
Returns
a list of all vertices belonging to the given community
Implements DynCommBaseInterface.
Definition at line 231 of file DynCommBase.h.
References GraphUndirectedGroupable::vertices().
weight()
typeWeight DynCommBase::weight (const typeVertex & source, const typeVertex & destination) const inline virtual
Returns
the weight of the edge
Implements DynCommBaseInterface.
Definition at line 401 of file DynCommBase.h.
References GraphUndirected::weight().
Referenced by DynCommRcpp::edgeWeight().
Member Data Documentation
algrthm
Algorithm DynCommBase::algrthm private
Definition at line 44 of file DynCommBase.h.
grph
GraphUndirectedGroupable DynCommBase::grph private
Definition at line 45 of file DynCommBase.h.
oldCommunities
typeCommunityList DynCommBase::oldCommunities private
Definition at line 69 of file DynCommBase.h.
prmtrs
ProgramParameters DynCommBase::prmtrs private
Definition at line 47 of file DynCommBase.h.
qlt
Criterion DynCommBase::qlt private
Definition at line 46 of file DynCommBase.h.
timeProcessing
uint64 DynCommBase::timeProcessing =0 private
total time used for processing
Definition at line 62 of file DynCommBase.h.
Referenced by addRemoveEdges(), and time().
timeStart
uint64 DynCommBase::timeStart =0 private
auxiliary time used to store the start time
Definition at line 57 of file DynCommBase.h.
Referenced by addRemoveEdges().
timeTotal
uint64 DynCommBase::timeTotal =0 private
total accumulated time used for processing
Definition at line 52 of file DynCommBase.h.
Referenced by time().
The documentation for this class was generated from the following file:
R-CRAN/src/base/Cpp/DynCommBase.h