DynComm: R-CRAN/src/base/Cpp/graphUndirectedGroupable.h File Reference
graphUndirectedGroupable.h File Reference
#include "mapReversable.h"
#include <math.h>
#include "graphUndirected.h"
#include "setUtilities.h"
Classes
class GraphUndirectedGroupable
Groupable Undirected Graph.
Typedefs
typedef typeVertex typeCommunity
Data type definition for a single community.
typedef MapReversable< typeVertex, typeCommunity > typeCommunityList
Indexed community list by vertex.
typedef typeCommunityList::const_iterator typeCommunityListIteratorConst
Indexed community list constant iterator.
typedef typeCommunityList::typePair typeCommunityListPair
Indexed community list pair as returned by the iterator.
typedef typeCommunityList::range_iterator_const typeCommunityListRangeIteratorConst
Indexed community list constant reverse iterator.
typedef typeCommunityList::typeRange typeCommunityListRange
Indexed community list range.
typedef typeCommunityList::typeRangePair typeCommunityListRangePair
Indexed community list range pair as returned by the reverse iterator.
typedef std::map< typeCommunity, typeWeight > typeCommunityEdges
Indexed community weight list.
typedef std::map< typeCommunity, typeWeight >::iterator typeCommunityEdgesIterator
Indexed community weight list iterator.
typedef std::pair< typeCommunity, typeWeight > typeCommunityEdgesPair
Indexed community weight list pair as returned by the iterator.
typedef std::map< typeCommunity, typeWeight >::const_iterator typeCommunityEdgesIteratorConst
Indexed community weight list constant iterator.
typedef std::pair< typeCommunityEdgesIterator, typeCommunityEdgesIterator > typeCommunityEdgesRange
Indexed community weight list range.
typedef std::pair< typeCommunityEdgesIteratorConst, typeCommunityEdgesIteratorConst > typeCommunityEdgesRangeConst
Indexed community weight list constant range.
typedef std::set< typeCommunity > typeCommunities
List of communities.
Variables
const typeCommunity noGroup =std::numeric_limits<typeCommunity>::max()
Typedef Documentation
typeCommunities
typedef std::set<typeCommunity> typeCommunities
List of communities.
Definition at line 124 of file graphUndirectedGroupable.h.
typeCommunity
typedef typeVertex typeCommunity
Data type definition for a single community.
The community and vertex data types must be interchangeable but this might change in the future so define as a different data type.
Definition at line 31 of file graphUndirectedGroupable.h.
typeCommunityEdges
typedef std::map<typeCommunity, typeWeight> typeCommunityEdges
Indexed community weight list.
Optimization data type used to store the sum of weights of a community
Definition at line 86 of file graphUndirectedGroupable.h.
typeCommunityEdgesIterator
typedef std::map<typeCommunity, typeWeight>::iterator typeCommunityEdgesIterator
Indexed community weight list iterator.
Definition at line 91 of file graphUndirectedGroupable.h.
typeCommunityEdgesIteratorConst
typedef std::map<typeCommunity, typeWeight>::const_iterator typeCommunityEdgesIteratorConst
Indexed community weight list constant iterator.
Definition at line 101 of file graphUndirectedGroupable.h.
typeCommunityEdgesPair
typedef std::pair<typeCommunity, typeWeight> typeCommunityEdgesPair
Indexed community weight list pair as returned by the iterator.
Definition at line 96 of file graphUndirectedGroupable.h.
typeCommunityEdgesRange
typedef std::pair<typeCommunityEdgesIterator,typeCommunityEdgesIterator> typeCommunityEdgesRange
Indexed community weight list range.
Defines a pair with two iterators to the beginning and end of the range. If the iterators are identical, the list is empty. The pair can change between calls if the list is modified.
Definition at line 110 of file graphUndirectedGroupable.h.
typeCommunityEdgesRangeConst
typedef std::pair<typeCommunityEdgesIteratorConst,typeCommunityEdgesIteratorConst> typeCommunityEdgesRangeConst
Indexed community weight list constant range.
Defines a pair with two constant iterators to the beginning and end of the range. If the iterators are identical, the list is empty. The pair can change between calls if the list is modified.
Definition at line 119 of file graphUndirectedGroupable.h.
typeCommunityList
typedef MapReversable<typeVertex,typeCommunity> typeCommunityList
Indexed community list by vertex.
Definition at line 36 of file graphUndirectedGroupable.h.
typeCommunityListIteratorConst
typedef typeCommunityList::const_iterator typeCommunityListIteratorConst
Indexed community list constant iterator.
Expanded type: std::map<typeVertex,typeCommunity>::const_iterator
Definition at line 44 of file graphUndirectedGroupable.h.
typeCommunityListPair
typedef typeCommunityList::typePair typeCommunityListPair
Indexed community list pair as returned by the iterator.
Expanded type: std::pair<typeVertex,typeCommunity>
Definition at line 52 of file graphUndirectedGroupable.h.
typeCommunityListRange
typedef typeCommunityList::typeRange typeCommunityListRange
Indexed community list range.
Defines a pair with two constant reverse iterators to the beginning and end of the range. If the iterators are identical, the list is empty. The pair can change between calls if the list is modified. Expanded type: std::pair<std::multimap<typeCommunity,typeVertex>::const_iterator,std::multimap<typeCommunity,typeVertex>::const_iterator>
Definition at line 72 of file graphUndirectedGroupable.h.
typeCommunityListRangeIteratorConst
typedef typeCommunityList::range_iterator_const typeCommunityListRangeIteratorConst
Indexed community list constant reverse iterator.
Expanded type: std::multimap<typeCommunity,typeVertex>::const_iterator
Definition at line 60 of file graphUndirectedGroupable.h.
typeCommunityListRangePair
typedef typeCommunityList::typeRangePair typeCommunityListRangePair
Indexed community list range pair as returned by the reverse iterator.
Expanded type: std::pair<typeCommunity,typeVertex>
Definition at line 80 of file graphUndirectedGroupable.h.
Variable Documentation
noGroup
const typeCommunity noGroup =std::numeric_limits<typeCommunity>::max()
special community that indicates NO COMMUNITY
Definition at line 129 of file graphUndirectedGroupable.h.
Referenced by GraphUndirectedGroupable::addEdge(), AlgorithmLouvain::community(), GraphUndirectedGroupable::community(), and GraphUndirectedGroupable::replaceCommunity().